# Generated by Django 4.1.7 on 2023-12-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliateApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='phone',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
