# Generated by Django 4.1.7 on 2023-12-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliateApi', '0002_affiliate_phone_alter_affiliate_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
