# Generated by Django 4.1.7 on 2023-12-21 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliateApi', '0003_affiliate_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_program', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_email', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_contry', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_city', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('conversation_summary', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliateApi.affiliate')),
            ],
        ),
    ]
