# Generated by Django 4.1.7 on 2023-12-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliateApi', '0003_affiliate_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='gender',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
