# Generated by Django 4.1.7 on 2024-01-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliateApi', '0004_lead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='lead_contry',
            new_name='lead_country',
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
