# Generated by Django 4.1.7 on 2023-12-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliateApi', '0004_affiliate_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliate',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='affiliate',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20),
        ),
    ]
