# Generated by Django 4.1.7 on 2024-01-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliateApi', '0005_rename_lead_contry_lead_lead_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
