# Generated by Django 4.1.7 on 2024-01-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliateApi', '0006_lead_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_phone_country_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
