# Generated by Django 4.1.7 on 2024-01-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliateApi', '0007_lead_lead_phone_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='conversation_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
