# Generated by Django 4.1.7 on 2024-01-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliateApi', '0008_alter_lead_conversation_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('not_contacted', 'Not Contacted'), ('engaged', 'Engaged'), ('converted', 'Converted'), ('lost', 'Lost')], max_length=20, null=True),
        ),
    ]
