# Generated by Django 4.1.7 on 2024-01-05 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliateApi', '0005_remove_affiliate_is_approved_affiliate_status'),
        ('affiliateApi', '0010_alter_lead_lead_status'),
    ]

    operations = [
    ]
