from django.urls import path, include
from . import views

urlpatterns = [
    path(
        "batches/",
        views.get_batches,
    ),
    path("batch-details/", views.batch_details, name="batch-details"),
    path("participant-details/", views.participant_details, name="participant-details"),
    path(
        "participant-so-in-batch/<str:email>/",
        views.participant_so_in_batch,
        name="participant-so-in-batch",
    ),
    path(
        "participant-so-and-invoices-in-batch/<str:email>/",
        views.participant_so_and_invoices_in_batch,
        name="participant-so-and-invoices-in-batch",
    ),
    path(
        "sales-persons/finances/",
        views.sales_persons_finances,
        name="sales-persons-finances",
    ),
    path(
        "participant-finances/",
        views.participant_finances,
        name="participant-finances",
    ),
    path("faculties/", views.get_faculties),
    path(
        "get-all-faculties/",
        views.get_all_faculties,
        name="get_all_faculties",
    ),
    path(
        "get-all-finance/",
        views.get_all_finance,
        name="get_all_finance",
    ),
    path(
        "get-all-client-invoice-of-participant-for-batch/<str:participant_id>/<int:batch_id>/",
        views.get_all_client_invoice_of_participant_for_batch,
        name="get_all_client_invoice_of_participant_for_batch",
    ),
    path(
        "get-participants-of-batch/<int:batch_id>/",
        views.get_participants_of_that_batch,
        name="get_participants_of_that_batch",
    ),
    path(
        "get-ctt-salesperson-individual/<int:salesperson_id>/",
        views.get_ctt_salesperson_individual,
        name="get_ctt_salesperson_individual",
    ),
    path(
        "get-card-data-for-dashboard-ctt/",
        views.get_card_data_for_dashboard_ctt,
        name="get_card_data_for_dashboard_ctt",
    ),
    path(
        "get-all-ctt-faculties/",
        views.get_all_ctt_faculties,
        name="get_all_ctt_faculties",
    ),
    path(
        "get-the-profitability-of-a-batch/<int:batch_id>/",
        views.get_the_profitability_of_a_batch,
        name="get_the_profitability_of_a_batch",
    ),
    path(
        "get-upcoming-sessions/",
        views.get_upcoming_sessions,
        name="get_upcoming_sessions",
    ),
    path(
        "get-past-sessions/",
        views.get_past_sessions,
        name="get_past_sessions",
    ),
    path(
        "get-all-sessions/<int:batch_id>/",
        views.get_all_sessions,
        name="get_all_sessions",
    ),
    path(
        "add-attendance-of-session/",
        views.add_attendance_of_session,
        name="add_attendance_of_session",
    ),
    path(
        "get-attendance-of-session/<int:session_id>/",
        views.get_attendance_of_session,
        name="get_attendance_of_session",
    ),
    path(
        "send-calendar-invites/",
        views.send_calendar_invites,
        name="send_calendar_invites",
    ),
]
