# Generated by Django 4.1.7 on 2023-05-15 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pmo', 'pmo'), ('coach', 'coach'), ('learner', 'learner'), ('hr', 'hr')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_id', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.CharField(blank=True, default='', max_length=10)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('domain', models.CharField(blank=True, max_length=50)),
                ('room_id', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=25)),
                ('level', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=20)),
                ('area_of_expertise', models.JSONField(blank=True, default=list)),
                ('completed_sessions', models.IntegerField(blank=True, default=0)),
                ('profile_pic', models.ImageField(blank=True, upload_to='post_images')),
                ('education', models.CharField(blank=True, max_length=200)),
                ('corporate_experience', models.TextField(blank=True)),
                ('coaching_experience', models.TextField(blank=True)),
                ('years_of_corporate_experience', models.CharField(blank=True, max_length=20)),
                ('years_of_coaching_experience', models.CharField(blank=True, max_length=20)),
                ('is_approved', models.BooleanField(blank=True, default=False)),
                ('location', models.JSONField(blank=True, default=list)),
                ('ctt_nctt', models.BooleanField(blank=True, default=False)),
                ('language', models.JSONField(blank=True, default=list)),
                ('min_fees', models.CharField(blank=True, max_length=120)),
                ('job_roles', models.JSONField(blank=True, default=list)),
                ('coaching_hours', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('edited_at', models.DateField(auto_now=True)),
                ('linkedin_profile_link', models.CharField(blank=True, max_length=500)),
                ('companies_worked_in', models.JSONField(blank=True, default=list)),
                ('other_certification', models.JSONField(blank=True, default=list)),
                ('active_inactive', models.BooleanField(blank=True, default=False)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
    ]
