# Generated by Django 4.1.7 on 2023-02-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pmo',
            old_name='user',
            new_name='profile',
        ),
    ]
