# Generated by Django 4.1.7 on 2023-05-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='fee_remark',
            field=models.TextField(blank=True),
        ),
    ]
