# Generated by Django 4.1.7 on 2023-02-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_user_pmo_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='meet_link',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
