# Generated by Django 4.1.7 on 2023-05-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_availibility_coachstatus_hr_learner_organisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_to_sold',
            field=models.BooleanField(default=False),
        ),
    ]
