# Generated by Django 4.1.7 on 2023-05-18 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_coachstatus_hr_learner_organisation_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=30)),
                ('end_time', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SessionRequestCaas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_booked', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_type', models.CharField(default='', max_length=50)),
                ('reschedule_request', models.JSONField(blank=True, default=list)),
                ('availibility', models.ManyToManyField(related_name='requested_availability', to='api.availibility')),
                ('coach', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.coach')),
                ('confirmed_availability', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_availability', to='api.availibility')),
                ('hr', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hr')),
                ('learner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.learner')),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
    ]
