# Generated by Django 4.1.7 on 2023-06-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_sold_project_updated_to_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequestcaas',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
