# Generated by Django 4.1.7 on 2023-05-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
