# Generated by Django 4.1.7 on 2023-07-05 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_engagement_sessionrequestcaas_is_archive_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='competency',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.TextField(),
        ),
    ]
