# Generated by Django 4.1.7 on 2023-07-06 11:30

from django.db import migrations, models


def populate_engagement_status(apps, schema_editor):
    Engagement = apps.get_model("api", "Engagement")
    Engagement.objects.all().update(status="active")


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_project_options_project_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engagement",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("archived", "Archived"),
                ],
                max_length=20,
            ),
        ),
        migrations.RunPython(populate_engagement_status),

    ]

