# Generated by Django 4.1.7 on 2023-06-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_engagement_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequestcaas',
            name='session_duration',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='sessionrequestcaas',
            name='session_number',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='sessionrequestcaas',
            name='status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
