# Generated by Django 4.1.7 on 2023-07-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_engagement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequestcaas',
            name='invitees',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
