# Generated by Django 4.1.7 on 2023-07-24 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sessionrequestcaas_invitees'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pmo',
            name='room_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='approx_coachee',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='coach_fees_per_hour',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='frequency_of_session',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='price_per_hour',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='sessionrequestcaas',
            name='pmo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pmo'),
        ),
    ]
