# Generated by Django 4.1.7 on 2023-06-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sessionrequestcaas_session_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionrequestcaas',
            name='session_duration',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sessionrequestcaas',
            name='session_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
