# Generated by Django 4.1.7 on 2023-09-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_coach_currency_pmo_room_id_project_approx_coachee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequestcaas',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='sessionrequestcaas',
            name='session_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
