# Generated by Django 4.1.7 on 2023-07-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_coach_currency_pmo_room_id_project_approx_coachee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
