# Generated by Django 4.1.7 on 2023-07-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_project_coach_fees_per_hour_project_price_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmo',
            name='room_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
