# Generated by Django 4.1.7 on 2023-06-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_sessionrequestcaas_session_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequestcaas',
            name='order',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
