# Generated by Django 4.1.7 on 2023-07-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_project_coach_fees_per_hour_project_price_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='approx_coachee',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='frequency_of_session',
            field=models.TextField(blank=True),
        ),
    ]
