# Generated by Django 4.1.7 on 2023-09-09 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_project_location'),
        ('api', '0010_sessionrequestcaas_status_updated_at_and_more'),
    ]

    operations = [
    ]
