# Generated by Django 4.1.7 on 2023-07-22 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_pmo_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequestcaas',
            name='pmo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pmo'),
        ),
    ]
