# Generated by Django 4.1.7 on 2023-09-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_project_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequestcaas',
            name='billable_session_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sessionrequestcaas',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
