# Generated by Django 4.1.7 on 2023-08-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_coachcontract_projectcontract_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontract',
            name='template_id',
            field=models.IntegerField(null=True),
        ),
    ]
