# Generated by Django 4.1.7 on 2023-09-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sessionrequestcaas_billable_session_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='client_companies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='coach',
            name='education_pic',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
        migrations.AddField(
            model_name='coach',
            name='educational_qualification',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='coach',
            name='internal_coach',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='coach',
            name='organization_of_coach',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='coach',
            name='reason_for_inactive',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
