# Generated by Django 4.1.7 on 2023-09-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sessionrequestcaas_billable_session_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='coach',
            name='rating',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
