# Generated by Django 4.1.7 on 2023-09-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20230909_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionrequestcaas',
            name='session_duration',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
