# Generated by Django 4.1.7 on 2023-09-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_sessionrequestcaas_session_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequestcaas',
            name='billable_session_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
