# Generated by Django 4.1.7 on 2023-09-28 06:44

import api.models
from django.db import migrations, models
from django.core.exceptions import ValidationError
import json

def change_field_data(apps, schema_editor):
    Coach = apps.get_model('api', 'Coach') 
    for coach in Coach.objects.all():
        try:
            domain_data = json.loads(coach.domain)
            education_data=json.loads(coach.education)
            if not domain_data:
                coach.domain = json.dumps(domain_data)
                coach.save()
            if not education_data:  
                coach.education=json.dumps(education_data)
                coach.save()
        except (json.JSONDecodeError, ValidationError):
            if coach.domain:
                coach.domain = json.dumps([coach.domain])
            else:
                coach.domain = json.dumps([])
                
            if coach.education:
                coach.education=json.dumps([coach.education])
            else:
                coach.education=json.dumps([])
                
            coach.save()
            
            

            
            

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_project_name'),
    ]

    operations = [
        migrations.RunPython(change_field_data),
        migrations.AddField(
            model_name='coach',
            name='client_companies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='coach',
            name='education_pic',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
        migrations.AddField(
            model_name='coach',
            name='education_upload_file',
            field=models.FileField(blank=True, upload_to='pdf_files', validators=[api.models.validate_pdf_extension]),
        ),
        migrations.AddField(
            model_name='coach',
            name='educational_qualification',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='coach',
            name='internal_coach',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='coach',
            name='organization_of_coach',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='coach',
            name='reason_for_inactive',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='coach',
            name='domain',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='coach',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
