# Generated by Django 4.1.7 on 2023-09-19 07:18

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_coach_client_companies_coach_education_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='education_upload_file',
            field=models.FileField(blank=True, upload_to='pdf_files', validators=[api.models.validate_pdf_extension]),
        ),
        migrations.AlterField(
            model_name='coach',
            name='domain',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='coach',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='coach',
            name='organization_of_coach',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coach',
            name='reason_for_inactive',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
