# Generated by Django 4.1.7 on 2023-09-29 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_coach_client_companies_coach_education_pic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardizedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(blank=True, choices=[('location', 'Location'), ('other_certification', 'Other Certification'), ('area_of_expertise', 'Industry'), ('job_roles', 'Job roles'), ('companies_worked_in', 'Companies worked in'), ('language', 'Language'), ('education', 'Education institutions'), ('domain', 'Functional Domain'), ('client_companies', 'Client companies')], max_length=50)),
                ('values', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StandardizedFieldRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.coach')),
                ('standardized_field_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.standardizedfield')),
            ],
        ),
    ]
