# Generated by Django 4.1.7 on 2023-10-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_coach_client_companies_coach_education_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], max_length=20, null=True),
        ),
    ]
