# Generated by Django 4.1.7 on 2023-10-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_coach_client_companies_coach_education_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
