# Generated by Django 4.1.7 on 2023-10-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_coach_client_companies_coach_education_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='coach',
            name='rating',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
