# Generated by Django 3.2.13 on 2023-08-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_coachcontract_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachcontract',
            name='response_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
