# Generated by Django 4.1.7 on 2023-10-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_coach_level_alter_coach_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
