# Generated by Django 4.1.7 on 2023-08-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_coachcontract_response_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontract',
            name='reminder_timestamp',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
