# Generated by Django 4.1.7 on 2023-10-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_project_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='phone',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
