# Generated by Django 4.1.7 on 2023-10-11 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_project_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_link', models.CharField(max_length=500)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('coaching_session_number', models.IntegerField(blank=True, default=None, null=True)),
                ('coaching_session_order', models.IntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoachSchedularAvailibilty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=30)),
                ('end_time', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coach')),
            ],
        ),
        migrations.CreateModel(
            name='SchedularParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchedularProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_structure', models.JSONField(blank=True, default=list)),
                ('hr', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchedularSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('availibility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coachschedularavailibilty')),
                ('coaching_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coachingsession')),
                ('enrolled_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schedularparticipants')),
            ],
        ),
        migrations.CreateModel(
            name='SchedularBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilitator', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('coaches', models.ManyToManyField(blank=True, to='api.coach')),
                ('participants', models.ManyToManyField(blank=True, to='api.schedularparticipants')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schedularproject')),
            ],
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('zoom_id', models.CharField(max_length=500)),
                ('live_session_number', models.IntegerField(blank=True, default=None, null=True)),
                ('live_session_order', models.IntegerField(blank=True, default=None, null=True)),
                ('attendees', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schedularbatch')),
            ],
        ),
        migrations.AddField(
            model_name='coachingsession',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schedularbatch'),
        ),
    ]
