# Generated by Django 4.1.7 on 2023-10-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_project_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='phone_country_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
