# Generated by Django 4.1.7 on 2023-10-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_coachingsession_coachschedularavailibilty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingsession',
            name='duration',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='livesession',
            name='duration',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
