# Generated by Django 4.1.7 on 2023-10-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_coach_phone_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='vendor_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
