# Generated by Django 4.1.7 on 2023-10-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_schedularproject_name_schedularproject_organisation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedularproject',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='coachschedularavailibilty',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='coachschedularavailibilty',
            name='start_time',
        ),
        migrations.AddField(
            model_name='coachschedularavailibilty',
            name='availibility',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='coachschedularavailibilty',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachschedularavailibilty',
            name='request_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RemoveField(
            model_name='coachschedularavailibilty',
            name='coach',
        ),
        migrations.AddField(
            model_name='coachschedularavailibilty',
            name='coach',
            field=models.ManyToManyField(blank=True, to='api.coach'),
        ),
    ]
