# Generated by Django 4.1.7 on 2023-10-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_schedularproject_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachschedularavailibilty',
            name='availibility',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
