# Generated by Django 4.1.7 on 2023-11-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_project_project_description_userloginactivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='phone',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
