# Generated by Django 4.1.7 on 2023-10-18 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_coachingsession_coachschedularavailibilty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedularproject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
