# Generated by Django 4.1.7 on 2023-11-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_learner_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginactivity',
            name='platform',
            field=models.CharField(blank=True, choices=[('caas', 'CAAS'), ('seeq', 'SEEQ'), ('vendor', 'VENDOR'), ('assessment', 'ASSESSMENT'), ('unknown', 'UNKNOWN')], max_length=225),
        ),
    ]
