# Generated by Django 4.1.7 on 2023-10-19 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_coachschedularavailibilty_availibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coachschedularavailibilty',
            old_name='availibility',
            new_name='availability',
        ),
    ]
