# Generated by Django 4.1.7 on 2023-11-07 07:57

from django.db import migrations, models


def set_existing_projects_to_active(apps, schema_editor):
    Project = apps.get_model("api", "Project")
    Project.objects.filter(status__isnull=True).update(status="active")


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_project_status"),
    ]

    operations = [
        migrations.RunPython(set_existing_projects_to_active),
    ]
