# Generated by Django 4.1.7 on 2023-11-09 06:00

from django.db import migrations


def update_coaches_domains(apps, schema_editor):
    Coach = apps.get_model("api", "Coach")
    # Get all coaches
    coaches = Coach.objects.all()
    # Update domains for each coach
    for coach in coaches:
        if coach.domain:
            # Check if the domain is a string
            if isinstance(coach.domain, str):
                # Split the string by ","
                domains_list = [
                    domain.strip()
                    for domain in coach.domain.split(",")
                    if domain.strip()
                ]
                # Update the coach's domain with the list
                coach.domain = domains_list
                coach.save()
            elif isinstance(coach.domain, list):
                domains_list = [
                    domain.strip() for domain in coach.domain if domain.strip()
                ]
                coach.domain = domains_list
                coach.save()
        else:
            # Set empty array if domain is null
            coach.domain = []
            coach.save()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0024_auto_20231107_1327"),
    ]

    operations = [
        migrations.RunPython(update_coaches_domains),
    ]
