# Generated by Django 4.1.7 on 2023-11-09 06:03

from django.db import migrations, models
from api.models import Coach, StandardizedField
import django.db.models.deletion


def populate_standardized_field(apps, schema_editor):
    data_object = {}

    all_coaches = Coach.objects.all()

    locations = set()
    other_certifications = set()
    areas_of_expertise = set()
    job_roles = set()
    companies_worked_in = set()
    languages = set()
    educations = set()
    domains = set()
    client_companies = set()

    for coach in all_coaches:
        locations.update(coach.location)
        other_certifications.update(coach.other_certification)
        areas_of_expertise.update(coach.area_of_expertise)
        job_roles.update(coach.job_roles)
        companies_worked_in.update(coach.companies_worked_in)
        languages.update(coach.language)
        educations.update(coach.education)
        domains.update(coach.domain)
        client_companies.update(coach.client_companies)

    locations_list = list(locations)
    other_certifications_list = list(other_certifications)
    areas_of_expertise_list = list(areas_of_expertise)
    job_roles_list = list(job_roles)
    companies_worked_in_list = list(companies_worked_in)
    languages_list = list(languages)
    educations_list = list(educations)
    domains_list = list(domains)
    client_companies_list = list(client_companies)

    data_object["location"] = locations_list
    data_object["other_certification"] = other_certifications_list
    data_object["area_of_expertise"] = areas_of_expertise_list
    data_object["job_roles"] = job_roles_list
    data_object["companies_worked_in"] = companies_worked_in_list
    data_object["language"] = languages_list
    data_object["education"] = educations_list
    data_object["domain"] = domains_list
    data_object["client_companies"] = client_companies_list

    for field_name, field_values in data_object.items():
        standardized_field, created = StandardizedField.objects.get_or_create(
            field=field_name
        )
        standardized_field.values = field_values
        standardized_field.save()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0025_update_coaches_domains"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardizedField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("location", "Location"),
                            ("other_certification", "Other Certification"),
                            ("area_of_expertise", "Industry"),
                            ("job_roles", "Job roles"),
                            ("companies_worked_in", "Companies worked in"),
                            ("language", "Language"),
                            ("education", "Education institutions"),
                            ("domain", "Functional Domain"),
                            ("client_companies", "Client companies"),
                        ],
                        max_length=50,
                    ),
                ),
                ("values", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StandardizedFieldRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coach",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.coach",
                    ),
                ),
                (
                    "standardized_field_name",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.standardizedfield",
                    ),
                ),
            ],
        ),
        migrations.RunPython(populate_standardized_field),
    ]
