# Generated by Django 4.1.7 on 2023-11-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_standardizedfield_standardizedfieldrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='coach_consent_mandatory',
            field=models.BooleanField(default=True),
        ),
    ]
