# Generated by Django 4.1.7 on 2023-11-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_project_coach_consent_mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('completed', 'Completed'), ('presales', 'Presales')], max_length=20, null=True),
        ),
    ]
