# Generated by Django 4.1.7 on 2023-11-28 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_standardizedfield_standardizedfieldrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoveCoachActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=225, null=True)),
                ('time_of_removal', models.DateTimeField()),
                ('removed_coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coach')),
                ('removed_from_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
    ]
