# Generated by Django 4.1.7 on 2023-11-30 13:16

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone
from api.models import CoachStatus ,Project,Template,ProjectContract,CoachContract

def populate_coach_contracts(apps, schema_editor):
    filtered_coach_statuses = CoachStatus.objects.filter(
            status__hr__status="select", status__project_structure__status="select"
        )
    projects = []
    coach_status_present_in_project=[]
    for coach_status in filtered_coach_statuses:
        try:
            project = Project.objects.get(coaches_status__id=coach_status.id)
            projects.append(project)
            coach_status_present_in_project.append(coach_status)
        except Project.DoesNotExist:
            coach_status.delete()
        
        
    contract_template , created1= Template.objects.get_or_create(
            title="Template 1", description='<h1><strong><u>Coaching Agreement for coaching project with InMuto Consulting Pvt Ltd</u></strong></h1><p class="ql-align-center"><br></p><p><br></p><p><br></p><p><span style="color: rgb(51, 51, 51);">This Coach agreement document outlines the terms under which you, an independent executive coach, agrees to be an approved Coach of&nbsp;InMuto Consulting Pvt Ltd, for a coaching assignment.</span></p><p><span style="color: rgb(51, 51, 51);">This is a specific agreement covering your affiliation with InMuto Consulting Pvt Ltd for Coaching assignment with </span><strong style="color: rgb(51, 51, 51);">{{org_name}}</strong><span style="color: rgb(51, 51, 51);">. This Project Coach Agreement is based on the client Statement of Work detailed in Scope of Services (Annexure A).</span></p><p><span style="color: rgb(51, 51, 51);">This agreement is current for this project unless replaced by another agreement, for which you will be notified. This agreement, in whole or in part, may not be shared outside of InMuto Consulting Pvt Ltd.</span></p><p><br></p><p><strong>Maintaining Authenticity and Quality</strong></p><p><br></p><p><span style="color: rgb(51, 51, 51);">Our organization believes in the concept of Authenticity and we will abide by our belief system at all times. We also hope that the same is showcased by you while working with us and our Client.</span></p><p><span style="color: rgb(51, 51, 51);">We wish to maintain a very high quality in delivering our engagements to our clients.</span></p><p><br></p><p><strong>Contract and Billing</strong></p><p><br></p><p><span style="color: rgb(51, 51, 51);">You agree that InMuto Consulting Pvt Ltd will handle the contracting and billing of assignments with </span><strong style="color: rgb(51, 51, 51);">{{org_name}}</strong><span style="color: rgb(51, 51, 51);">.</span></p><p><span style="color: rgb(51, 51, 51);">You will be billing InMuto Consulting Pvt Ltd for this engagement. </span></p><p><span style="color: rgb(51, 51, 51);">You will send the invoices to </span><a href="mailto:finance@coachtotransformation.com" rel="noopener noreferrer" target="_blank" style="color: rgb(51, 51, 51);">finance@meeraq.com.</a><span style="color: rgb(51, 51, 51);"> </span></p><p><span style="color: rgb(51, 51, 51);">You can raise an invoice at the end of the financial quarter. Payment will be made 30-35 from the day of invoice raised. All the invoices to be raised against the purchase order provided by the PMO</span></p><p><span style="color: rgb(51, 51, 51);">&nbsp;</span></p><p><span style="color: rgb(51, 51, 51);">For project management support, you will reach out to </span><em style="color: rgb(51, 51, 51);">pmocoaching@meeraq.com</em><span style="color: rgb(51, 51, 51);">.</span></p><p><br></p><p><br></p><p><strong style="color: rgb(51, 51, 51);">Use of Coach-as-a-Service (CaaS) Platform</strong></p><p><br></p><p><span style="color: rgb(51, 51, 51);">You are committing to record your time and assignment details as requested for this assignment in CaaS, our online tracking platform for all coaching engagements.</span></p><p><span style="color: rgb(51, 51, 51);">&nbsp;</span></p><p><span style="color: rgb(51, 51, 51);">Our CaaS system is our official record of your work and is used for client reporting, billing and coach payments. Payments will be made against the sessions recorded in CaaS and no offline mode will be accepted.</span></p><p><br></p><p><br></p><p><strong>Additional Work</strong></p><p><br></p><p><span style="color: rgb(51, 51, 51);">If a client contacts you to discuss additional work you will pass the enquiry onto the relevant Client Relationship Manager or Partner from InMuto Consulting Pvt Ltd.</span></p><p><br></p><p><br></p><p><strong>No Poaching Clause</strong></p><p><br></p><p><span style="color: rgb(51, 51, 51);">You agree to not approach the client organization for any work for 2 years beyond the end of the coaching engagement.</span></p><p><br></p><p><br></p><p><strong>Non-Disclosure Agreement</strong></p><p><br></p><p><span style="color: rgb(51, 51, 51);">The parties have agreed to provide each other with information which they consider to be confidential in nature (the “Confidential Information”). The “Purpose” is to enable the Coach to provide services on behalf of InMuto Consulting Pvt Ltd as a consultant to the client.</span></p><p><span style="color: rgb(51, 51, 51);">In consideration of each of the parties disclosing to the other Confidential Information, the parties hereby undertake that they shall:</span></p><ol><li><span style="color: rgb(51, 51, 51);">Not communicate, disclose or make available all or any part of the Confidential Information to any third party</span></li><li><span style="color: rgb(51, 51, 51);">Not directly or indirectly use, or permit others to use, the Confidential Information other than for the Purpose</span></li><li><span style="color: rgb(51, 51, 51);">Not make any announcement or disclosure in connection with the Confidential Information or the Purpose without the prior written consent of the other party</span></li></ol><p><br></p><p><br></p><p><span style="color: rgb(51, 51, 51);">All rights in the Confidential Information are reserved by the party to which it belongs and no rights or obligations other than those expressly set out in this agreement are granted or to be implied from this agreement. In particular no license is granted directly or indirectly by this agreement relating to any intervention, discovery, patent, copyright or other industrial or intellectual property right now or in the future held, made, obtained or licensable by either party.</span></p><p><strong style="color: rgb(51, 51, 51);">Governing Laws</strong></p><p><br></p><p><span style="color: rgb(51, 51, 51);">The rights, duties and obligations of the parties and the validity, interpretation, performance, and legal effect of this agreement shall be governed and determined by the laws within the country of permanent location of InMuto Consulting Pvt Ltd and the parties hereby submit to the non-exclusive jurisdiction of the courts within the country of permanent location.</span></p><p><br></p><p><strong>Indemnity Waiver</strong></p><p><br></p><p><span style="color: rgb(51, 51, 51);">The Coach will defend, indemnify, and hold InMuto Consulting Pvt Ltd, its officers, partners, employees, and agents harmless from any claims, losses, liabilities, damages, expenses, and costs (including attorneys’ fees and court costs) (collectively, "Losses") resulting from any act or omission by Coach in the course of performing the Services under this Agreement.</span></p><p><br></p><p><strong style="color: rgb(51, 51, 51);">Non-Performance</strong></p><p><br></p><p><span style="color: rgb(51, 51, 51);">InMuto Consulting Pvt Ltd will not be liable to make any payments if the Engagement is terminated by the Client or Coachee due to non-performance of the&nbsp;Coach.</span></p><p><br></p><p><strong>Termination</strong></p><p><br></p><ul><li><span style="color: rgb(51, 51, 51);">The contract will terminate at the end of the engagement unless a renewal is agreed upon.</span></li></ul><p><br></p><ul><li><span style="color: rgb(51, 51, 51);">The contract can also be terminated without cause by InMuto Consulting Pvt Ltd anytime during the engagement.</span></li></ul><p><br></p><ul><li><span style="color: rgb(51, 51, 51);">If the Coach wishes to terminate the contract, then the Coach will provide 30 days’ notice for termination.</span></li></ul><h1 class="ql-align-justify"><br></h1><p class="ql-align-justify"><strong>Expenses and Travel</strong></p><p class="ql-align-justify"><br></p><p class="ql-align-justify"><span style="color: rgb(51, 51, 51);">You agree to abide by whatever expense policies our client may have. This applies to travel, rates, documentation requirements, use of travel services, etc. Expenses are usual and customary and actual</span></p><p><span style="color: rgb(51, 51, 51);">cost. Unless the client asks for the original receipts, we ask that you keep receipts on file in your offices and simply report the expense as a separate invoice that we can bill to the client.</span></p>'
        )
    for project in projects:
        desc = contract_template.description.replace("{{org_name}}", project.organisation.name)
        project_contract,created2 = ProjectContract.objects.get_or_create(
                template_id=contract_template.id,
                title=contract_template.title,
                content=desc,
                project=project,
            )
    coach_contracts=[]
    for coach_status in coach_status_present_in_project:
        project = Project.objects.get(coaches_status__id=coach_status.id)
        project_contract = ProjectContract.objects.get( template_id=contract_template.id,project=project)
        coach_contract,created3=CoachContract.objects.get_or_create(
                project_contract=project_contract,
                name_inputed=coach_status.coach.first_name + " " + coach_status.coach.last_name,
                project=project,
                status="approved",
                coach=coach_status.coach,
                response_date=timezone.now().date()
            )
        coach_contracts.append(coach_contract)
    print(coach_contracts)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_sessionrequestedactivity_removecoachactivity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.IntegerField(null=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_timestamp', models.CharField(blank=True, max_length=30)),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='CoachContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_inputed', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('send_date', models.DateField(auto_now_add=True)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coach')),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('project_contract', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.projectcontract')),
            ],
        ),
        migrations.RunPython(populate_coach_contracts),
    ]
