# Generated by Django 4.1.7 on 2023-12-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_sessionrequestedactivity_removecoachactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastsessionactivity',
            name='session_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
