# Generated by Django 4.1.7 on 2023-11-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_sessionrequestedactivity'),
        ('api', '0030_alter_removecoachactivity_user'),
    ]

    operations = [
    ]
