# Generated by Django 4.1.7 on 2023-12-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_pastsessionactivity_session_name'),
        ('api', '0030_alter_project_status_update'),
    ]

    operations = [
    ]
