# Generated by Django 4.1.7 on 2023-12-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_pastsessionactivity_session_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enable_emails_to_hr_and_coachee',
            field=models.BooleanField(default=True),
        ),
    ]
