# Generated by Django 4.1.7 on 2023-12-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_sharecoachprofileactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharecoachprofileactivity',
            name='coach',
        ),
        migrations.AddField(
            model_name='sharecoachprofileactivity',
            name='coaches',
            field=models.ManyToManyField(blank=True, to='api.coach'),
        ),
    ]
