# Generated by Django 4.1.7 on 2023-12-11 14:05

from django.db import migrations, models


def assign_roles_to_profiles(apps, schema_editor):
    Profile = apps.get_model("api", "Profile")
    Role = apps.get_model("api", "Role")

    # Assign roles to existing profiles based on the user's type
    for profile in Profile.objects.all():
        if profile.type == "hr":
            role_name = "hr"
        elif profile.type == "learner":
            role_name = "learner"
        elif profile.type == "coach":
            role_name = "coach"
        elif profile.type == "pmo":
            role_name = "pmo"
        else:
            # Handle any other cases or set a default role
            role_name = "default"

        role, created = Role.objects.get_or_create(name=role_name)
        profile.roles.add(role)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0033_project_enable_emails_to_hr_and_coachee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="roles",
            field=models.ManyToManyField(to="api.role"),
        ),
        migrations.RunPython(assign_roles_to_profiles),
        migrations.RemoveField(
            model_name="profile",
            name="type",
        ),
    ]
