# Generated by Django 4.1.7 on 2023-12-18 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_role_remove_profile_type_profile_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_shared_count', models.PositiveIntegerField(default=0)),
                ('projects_finalized_count', models.PositiveIntegerField(default=0)),
                ('projects_done_chem_count', models.PositiveIntegerField(default=0)),
                ('coachee_projects_finalized_count', models.PositiveIntegerField(default=0)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coach')),
            ],
        ),
    ]
