# Generated by Django 4.1.7 on 2023-12-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_coachactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachactivity',
            name='project_id_array',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
