# Generated by Django 4.1.7 on 2024-01-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_trim_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='masked_coach_profile',
            field=models.BooleanField(default=False),
        ),
    ]
