# Generated by Django 4.1.7 on 2024-01-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_trim_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='meet_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='teams_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='zoom_link',
            field=models.TextField(blank=True),
        ),
    ]
