# Generated by Django 4.1.7 on 2024-01-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_project_masked_coach_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='automated_reminder',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
