# Generated by Django 4.1.7 on 2024-02-17 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_standardizedfield_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='coach_id',
        ),
    ]
