# Generated by Django 4.1.7 on 2024-02-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_remove_coach_coach_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachstatus',
            name='is_consent_asked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coachstatus',
            name='project_structure',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
