# Generated by Django 4.1.7 on 2024-03-03 12:08

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='coaching_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='corporate_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='education_pic',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='education_upload_file',
            field=models.FileField(blank=True, upload_to='pdf_files', validators=[api.models.validate_pdf_extension]),
        ),
    ]
