# Generated by Django 4.1.7 on 2024-03-04 05:10

from django.db import migrations, models
from django.db import transaction


def populate_project_structure_in_coach_status(apps, schema):
    try:
        with transaction.atomic():
            Project = apps.get_model("api", "Project")

            projects = Project.objects.all()

            for project in projects:
                project_structure = project.project_structure
                
                for coach_status in project.coaches_status.all():
                    if project.steps["project_structure"]["status"] == "complete":
                        coach_status.project_structure = project_structure
                    else:
                        coach_status.project_structure = []
                    coach_status.save()

    except Exception as e:
        print(str(e))


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_facilitator_coaching_experience_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachstatus",
            name="is_consent_asked",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="coachstatus",
            name="project_structure",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(populate_project_structure_in_coach_status),
    ]
