# Generated by Django 4.1.7 on 2024-03-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_facilitator_coaching_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachstatus',
            name='is_consent_asked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coachstatus',
            name='project_structure',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
