# Generated by Django 4.1.7 on 2024-03-05 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_facilitator_coaching_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmo',
            name='sub_role',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('junior_pmo', 'Junior PMO')], max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='junior_pmo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pmo'),
        ),
        migrations.AlterField(
            model_name='update',
            name='pmo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pmo'),
        ),
    ]
