# Generated by Django 4.1.7 on 2024-03-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_coachstatus_is_consent_asked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequestcaas',
            name='is_extra',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
