# Generated by Django 4.1.7 on 2024-03-09 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_project_calendar_invites_project_email_reminder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='automated_reminder',
        ),
    ]
