# Generated by Django 5.0.3 on 2024-03-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_facilitator_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequestcaas',
            name='auto_generated_status',
            field=models.CharField(blank=True, default='pending', max_length=50),
        ),
    ]
