# Generated by Django 4.1.7 on 2024-03-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_facilitator_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='automated_reminder',
        ),
        migrations.AddField(
            model_name='project',
            name='calendar_invites',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='email_reminder',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='whatsapp_reminder',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
