# Generated by Django 5.0.3 on 2024-03-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_remove_project_automated_reminder_pmo_sub_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachcontract',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
