# Generated by Django 4.1.7 on 2024-03-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_remove_project_automated_reminder_pmo_sub_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequestcaas',
            name='auto_generated_status',
            field=models.CharField(blank=True, default='pending', max_length=50),
        ),
    ]
