# Generated by Django 4.1.7 on 2024-03-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_remove_project_automated_reminder_pmo_sub_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='active_inactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='active_inactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='learner',
            name='active_inactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pmo',
            name='active_inactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='active_inactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='active_inactive',
            field=models.BooleanField(default=True),
        ),
    ]
