# Generated by Django 4.1.7 on 2024-03-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_pmo_sub_role_project_junior_pmo_alter_update_pmo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmo',
            name='sub_role',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('junior_pmo', 'Junior PMO')], default='manager', max_length=50),
        ),
    ]
