# Generated by Django 4.1.7 on 2024-03-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_sessionrequestcaas_auto_generated_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachstatus',
            name='purchase_order_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='coachstatus',
            name='purchase_order_no',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='finance',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
