# Generated by Django 4.1.7 on 2024-03-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_sessionrequestcaas_auto_generated_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='job_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='learner',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
    ]
