# Generated by Django 4.1.7 on 2024-03-26 10:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_learner_job_roles_learner_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='education_upload_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf_files', validators=[api.models.validate_pdf_extension]),
        ),
    ]
