# Generated by Django 4.1.7 on 2024-03-18 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_learner_job_roles_learner_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardizedfieldrequest',
            name='learner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.learner'),
        ),
    ]
