# Generated by Django 4.1.7 on 2024-03-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_learner_job_roles_learner_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
