# Generated by Django 4.1.7 on 2024-03-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_learner_job_roles_learner_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachcontract',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
