# Generated by Django 4.1.7 on 2024-03-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_coachstatus_purchase_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='active_inactive',
            field=models.BooleanField(default=True),
        ),
    ]
