# Generated by Django 4.1.7 on 2024-04-02 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0050_coachstatus_purchase_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('expires_at', models.CharField(blank=True, max_length=225)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
