# Generated by Django 4.1.7 on 2024-04-03 05:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_coachstatus_purchase_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='education_upload_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf_files', validators=[api.models.validate_pdf_extension]),
        ),
    ]
