# Generated by Django 4.1.7 on 2024-04-03 10:44

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_coach_education_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='certificate_one',
            field=models.FileField(blank=True, null=True, upload_to='pdf_files', validators=[api.models.validate_pdf_extension]),
        ),
        migrations.AddField(
            model_name='coach',
            name='certificate_two',
            field=models.FileField(blank=True, null=True, upload_to='pdf_files', validators=[api.models.validate_pdf_extension]),
        ),
    ]
