# Generated by Django 4.1.7 on 2024-04-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
