# Generated by Django 4.1.7 on 2024-04-11 06:06

from django.db import migrations


def update_tasks(apps, schema):
    api_task = apps.get_model("api", "Task")
    schedular_task = apps.get_model("schedularApi", "Task")
    for task in api_task.objects.all():
        new_task = schedular_task.objects.create(
            task=task.task,
            caas_project=task.caas_project,
            session_caas=task.session_caas,
            coach=task.coach,
            engagement=task.engagement,
            goal=task.goal,
            vendor_user=task.vendor_user,
            priority=task.priority,
            status=task.status,
            remarks=task.remarks,
            trigger_date=task.trigger_date,
            project_type="caas",
            created_at=task.created_at,
            updated_at=task.updated_at,
        )
        new_task.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0052_sales"),
        ("schedularApi", "0025_task"),
    ]

    operations = [
        migrations.RunPython(update_tasks),
        migrations.DeleteModel(
            name="Task",
        ),
    ]
