# Generated by Django 4.1.7 on 2024-04-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableHiddenColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(blank=True, max_length=225)),
                ('hidden_columns', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='coach',
            name='is_coach',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='coach',
            name='is_consultant',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='coach',
            name='is_mentor',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='coach',
            name='remark',
            field=models.TextField(blank=True),
        ),
    ]
