# Generated by Django 4.1.7 on 2024-04-12 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sales_person_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='goal',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.engagement'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('archive', 'Archive'), ('complete', 'Complete')], max_length=20, null=True),
        ),
    ]
