# Generated by Django 5.0.3 on 2024-04-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='is_rejected',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='is_rejected',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
