# Generated by Django 4.1.7 on 2024-04-12 12:49

from django.db import migrations, models
import django.db.models.deletion


def populate_action_items(apps, schema_editor):
    try:

        Competency = apps.get_model("api", "Competency")
        GoalCompetencyMapping = apps.get_model("api", "GoalCompetencyMapping")
        ActionItem = apps.get_model("api", "ActionItem")

        for competency in Competency.objects.all():
            goal_competency = GoalCompetencyMapping.objects.create(
                goal=competency.goal, competency=competency, scoring=competency.scoring
            )
            action_items = ActionItem.objects.filter(competency=competency)
            for action_item in action_items:
                action_item.goal_competency = goal_competency
                action_item.save()
    except Exception as e:
        print(e)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_sales_sales_person_id_alter_goal_engagement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoalCompetencyMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scoring", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "competency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.competency",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.goal",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="actionitem",
            name="goal_competency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.goalcompetencymapping",
            ),
        ),
        migrations.RunPython(populate_action_items),
        migrations.RemoveField(
            model_name="actionitem",
            name="competency",
        ),
        migrations.RemoveField(
            model_name="competency",
            name="goal",
        ),
        migrations.RemoveField(
            model_name="competency",
            name="scoring",
        ),
        migrations.AlterField(
            model_name="competency",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
