# Generated by Django 4.1.7 on 2024-04-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_tablehiddencolumn_coach_is_coach_coach_is_consultant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='is_rejected',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='is_rejected',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
