# Generated by Django 5.0.3 on 2024-04-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_sales_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='is_rejected',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
