# Generated by Django 4.1.7 on 2024-04-29 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_coach_is_rejected_facilitator_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
        migrations.AddField(
            model_name='pmo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
        migrations.AddField(
            model_name='sales',
            name='business',
            field=models.CharField(blank=True, default='meeraq', max_length=255),
        ),
        migrations.AddField(
            model_name='sales',
            name='sales_person_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='goal',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.engagement'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('archive', 'Archive'), ('complete', 'Complete')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='CTTPmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('active_inactive', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
    ]
