# Generated by Django 5.0.3 on 2024-04-19 12:22

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_sales_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 4, 19, 12, 22, 47, 41870, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
