# Generated by Django 5.0.3 on 2024-04-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_actionitem_created_at_goal_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='competency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
