# Generated by Django 4.1.7 on 2024-05-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_hr_profile_pic_pmo_profile_pic_sales_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='nudges',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='post_assessment',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pre_assessment',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
