# Generated by Django 4.1.7 on 2024-05-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_hr_profile_pic_pmo_profile_pic_sales_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_project_structure',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_credits',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
