# Generated by Django 4.1.7 on 2024-05-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_engagement_type_project_credit_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('COD', 'COD'), ('4+2', '4+2'), ('CAAS', 'CAAS')], default='CAAS', max_length=50),
        ),
    ]
