# Generated by Django 4.1.7 on 2024-05-01 09:51

from django.db import migrations, models
import django.db.models.deletion
from django.db import transaction


def populate_engagement_in_session(apps, schema_editor):
    try:
        with transaction.atomic():
            SessionRequestCaas = apps.get_model("api", "SessionRequestCaas")
            Engagement = apps.get_model("api", "Engagement")
            for session in SessionRequestCaas.objects.all():
                engagement = Engagement.objects.filter(
                    learner=session.learner, project=session.project
                ).first()
                session.engagement = engagement
                session.save()

    except Exception as e:
        print(str(e))


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_project_is_project_structure_project_total_credits"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionrequestcaas",
            name="engagement",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.engagement",
            ),
        ),
        migrations.RunPython(populate_engagement_in_session)
    ]
