# Generated by Django 4.1.7 on 2024-05-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_engagement_type_project_credit_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='request_expiry_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_credits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
