# Generated by Django 4.1.7 on 2024-05-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_project_request_expiry_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequestcaas',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
