# Generated by Django 4.1.7 on 2024-05-07 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_project_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.coach'),
        ),
        migrations.AlterField(
            model_name='update',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.project'),
        ),
    ]
