# Generated by Django 4.1.7 on 2024-05-08 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def update_tasks(apps, schema):
    api_task = apps.get_model("api", "Task")
    schedular_task = apps.get_model("schedularApi", "Task")
    for task in api_task.objects.all():
        new_task = schedular_task.objects.create(
            task=task.task,
            caas_project=task.caas_project,
            session_caas=task.session_caas,
            coach=task.coach,
            engagement=task.engagement,
            goal=task.goal,
            vendor_user=task.vendor_user,
            priority=task.priority,
            status=task.status,
            remarks=task.remarks,
            trigger_date=task.trigger_date,
            project_type="caas",
            created_at=task.created_at,
            updated_at=task.updated_at,
        )
        new_task.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0057_alter_project_project_type'),
        ("schedularApi", "0028_expense_coach_expense_session_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('active_inactive', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
        migrations.AddField(
            model_name='tablehiddencolumn',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='update',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.coach'),
        ),
        migrations.AlterField(
            model_name='update',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.project'),
        ),
        migrations.RunPython(update_tasks),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
