# Generated by Django 4.1.7 on 2024-05-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_sessionrequestcaas_engagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration_of_each_session',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
