# Generated by Django 4.1.7 on 2024-05-10 07:08

from django.db import migrations, models

def populate_area_of_expertise(apps, schema):
    Learner = apps.get_model("api", "Learner")
    learners = Learner.objects.all()
    learners.update(area_of_expertise="")

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_leader_tablehiddencolumn_user_update_coach_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_area_of_expertise),
        migrations.AlterField(
            model_name='learner',
            name='area_of_expertise',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
