# Generated by Django 4.1.7 on 2024-05-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_project_duration_of_each_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='request_expiry_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
