# Generated by Django 4.1.7 on 2024-05-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_sessionrequestcaas_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_session_expiry',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
