# Generated by Django 4.1.7 on 2024-05-10 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_alter_learner_area_of_expertise'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachProfileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.JSONField(blank=True, default=list)),
                ('masked_coach_profile', models.BooleanField(default=False)),
                ('unique_id', models.CharField(blank=True, max_length=225, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coaches', models.ManyToManyField(blank=True, to='api.coach')),
            ],
        ),
        migrations.AddField(
            model_name='coachprofiletemplate',
            name='coach_profile_share',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.coachprofileshare'),
        ),
    ]
