# Generated by Django 4.1.7 on 2024-05-02 13:10

from django.db import migrations, models
from django.db import transaction

def populate_engagement(apps, schema_editor):
    try:
        with transaction.atomic():
            Engagement = apps.get_model("api", "Engagement")
            for engagement in Engagement.objects.all():
                if engagement.project.is_project_structure:
                    engagement.type = "caas" 
                else:
                    engagement.type = "cod"
                
                engagement.save()
    except Exception as e:
        print(str(e))

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_project_request_expiry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='type',
            field=models.CharField(blank=True, choices=[('cod', 'COD'), ('caas', 'CAAS')], max_length=225, null=True),
        ),
        migrations.RunPython(populate_engagement)
    ]
