# Generated by Django 4.1.7 on 2024-05-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_engagement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='credit_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
