# Generated by Django 4.1.7 on 2024-05-13 13:21

from django.db import migrations



def update_contracts(apps, schema):

    api_coach_contract = apps.get_model("api", "CoachContract")
    api_project_contract = apps.get_model("api", "ProjectContract")
    schedular_coach_contract = apps.get_model("schedularApi", "CoachContract")
    schedular_project_contract = apps.get_model("schedularApi", "ProjectContract")

    for api_project_instance in api_project_contract.objects.all():

        schedular_project_instance = schedular_project_contract.objects.create(
            template_id=api_project_instance.template_id,
            title=api_project_instance.title,
            content=api_project_instance.content,
            project=api_project_instance.project,
            created_at=api_project_instance.created_at,
            updated_at=api_project_instance.updated_at,
            reminder_timestamp=api_project_instance.reminder_timestamp,
        )
        schedular_project_instance.save()


    for api_coach_instance in api_coach_contract.objects.all():

        new_project_contract = schedular_project_contract.objects.filter(
            project=api_coach_instance.project
        ).first()

        schedular_coach_instance = schedular_coach_contract.objects.create(
            project_contract=new_project_contract,
            name_inputed=api_coach_instance.name_inputed,
            project=api_coach_instance.project,
            status=api_coach_instance.status,
            coach=api_coach_instance.coach,
            send_date=api_coach_instance.send_date,
            response_date=api_coach_instance.response_date,
            created_at=api_coach_instance.created_at,

        )
        schedular_coach_instance.save()




class Migration(migrations.Migration):

    dependencies = [
        ("schedularApi", "0031_alter_livesession_session_type_projectcontract_and_more"),
    ]

    operations = [
        migrations.RunPython(update_contracts),
        
        migrations.RemoveField(
            model_name='projectcontract',
            name='project',
        ),
        migrations.DeleteModel(
            name='CoachContract',
        ),
        migrations.DeleteModel(
            name='ProjectContract',
        ),
    ]
