# Generated by Django 4.1.7 on 2024-05-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_coachprofileshare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofileshare',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
