# Generated by Django 4.1.7 on 2024-05-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_alter_standardizedfield_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='nudges',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='post_assessment',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pre_assessment',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
