# Generated by Django 4.1.7 on 2024-05-27 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('api', '0063_alter_standardizedfield_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='nudge_frequency',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='nudge_periodic_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask'),
        ),
        migrations.AddField(
            model_name='project',
            name='nudge_start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='nudges',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='post_assessment',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pre_assessment',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('bulk_upload_of_coach', 'Bulk Upload of Coach'), ('bulk_upload_of_facilitator', 'Bulk Upload of Facilitator'), ('bulk_upload_of_batch', 'Bulk Upload of Batch'), ('bulk_upload_of_questions', 'Bulk Upload of Questions'), ('bulk_upload_of_participant', 'Bulk Upload of Participant'), ('assigning_certificate', 'Assigning Certificate'), ('assign_the_course', 'Assign the Course'), ('requesting_availability_of_coach', 'Requesting Availability of Coach'), ('adding_facilitator', 'Adding Facilitator'), ('adding_coach', 'Adding Coach'), ('editing_coach', 'Editing Coach'), ('editing_facilitator', 'Editing Facilitator'), ('editing_coachee', 'Editing Coachee'), ('video_upload_inside_lesson', 'Video Upload inside Lesson'), ('video_upload_inside_video_library', 'Video Upload Inside Video Library'), ('pdf_upload_inside_lesson', 'PDF Upload inside Lesson'), ('pdf_upload_inside_pdf_library', 'PDF Upload Inside PDF Library'), ('coach_editing_the_profile', 'Coach Editing the Profile'), ('coach_giving_his_availability', 'Coach Giving his Availability'), ('learner_requesting_a_session', 'Learner Requesting a Session'), ('learner_editing_the_profile', 'Learner Editing the Profile'), ('learner_course_engagement', 'Learner Course Engagement'), ('facilitator_editing_profile', 'Facilitator Editing Profile'), ('hr_downloading_report', 'HR Downloading Report')], max_length=100)),
                ('response', models.BooleanField(blank=True)),
                ('comments', models.TextField(blank=True, default='')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.coach')),
                ('facilitator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.facilitator')),
                ('hr', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.hr')),
                ('learner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.learner')),
                ('pmo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pmo')),
            ],
        ),
    ]
