# Generated by Django 4.1.7 on 2024-05-27 06:31

from django.db import migrations, models


def populate_is_otp_verified(apps, schema):
    try:

        Coach = apps.get_model("api", "Coach")
        Facilitator = apps.get_model("api", "Facilitator")

        for coach_instance in Coach.objects.all():

            coach_instance.is_otp_verified = True
            coach_instance.save()

        for facilitator_instance in Facilitator.objects.all():

            facilitator_instance.is_otp_verified = True
            facilitator_instance.save()

    except Exception as e:
        print(str(e))

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_alter_standardizedfield_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='is_otp_verified',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='is_otp_verified',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.RunPython(populate_is_otp_verified),
    ]
