# Generated by Django 4.1.7 on 2024-05-30 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_chathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chathistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
