# Generated by Django 4.1.7 on 2024-06-10 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_coach_is_otp_verified_facilitator_is_otp_verified'),
        ('api', '0070_facilitator_remarks'),
    ]

    operations = [
    ]
