# Generated by Django 4.1.7 on 2024-06-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_facilitator_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_ngo_project',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
