# Generated by Django 4.1.7 on 2024-06-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_facilitator_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitator',
            name='remarks',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
