# Generated by Django 4.1.7 on 2024-06-13 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_coach_coaching_type_coach_competency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='info_summary',
            new_name='intro_summary',
        ),
    ]
