# Generated by Django 4.1.7 on 2024-06-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_coach_coaching_type_coach_competency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
