# Generated by Django 4.1.7 on 2024-06-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_cttfaculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ctt_pmo', 'CTT PMO'), ('pmo', 'Meeraq PMO'), ('curriculum', 'Curriculum'), ('sales', 'Sales'), ('finance', 'Finance')], max_length=20, null=True),
        ),
    ]
