# Generated by Django 4.1.7 on 2024-06-29 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0074_chathistory_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cttfaculty',
            name='is_assessor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
