# Generated by Django 4.1.7 on 2023-10-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedata',
            name='customer_name',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='invoicedata',
            name='signature',
            field=models.ImageField(blank=True, default='', upload_to='vendors-signature'),
        ),
        migrations.AlterField(
            model_name='invoicedata',
            name='type_of_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoicedata',
            name='vendor_billing_address',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='invoicedata',
            name='vendor_email',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='invoicedata',
            name='vendor_name',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
