# Generated by Django 4.1.7 on 2023-10-17 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapi', '0002_alter_invoicedata_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedata',
            name='signature',
        ),
    ]
