# Generated by Django 4.1.7 on 2023-10-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapi', '0002_alter_invoicedata_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedata',
            name='customer_address',
            field=models.TextField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='invoicedata',
            name='vendor_billing_address',
            field=models.TextField(blank=True, default=None, max_length=200),
        ),
    ]
