# Generated by Django 4.1.7 on 2023-12-11 14:05

from django.db import migrations, models
import django.db.models.deletion


from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


def create_vendor_from_coach_profiles(apps, schema_editor):
    Coach = apps.get_model("api", "Coach")
    Vendor = apps.get_model("zohoapi", "Vendor")
    Profile = apps.get_model("api", "Profile")  # Adjust the app name accordingly
    Role = apps.get_model("api", "Role")

    # Create the 'vendor' role if it doesn't exist
    vendor_role, created = Role.objects.get_or_create(name="vendor")
    # Filter Coach profiles with non-empty vendor_id
    coaches_with_vendor_id = Coach.objects.filter(~Q(vendor_id=""))

    for coach in coaches_with_vendor_id:
        profile = coach.user
        profile.roles.add(vendor_role)
        profile.save()
        # Create a Vendor instance for each coach with a vendor_id
        vendor_instance = Vendor.objects.create(
            user=profile,
            name=coach.first_name + " " + coach.last_name,
            phone=coach.phone,
            email=coach.email,
            vendor_id=coach.vendor_id,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0034_role_remove_profile_type_profile_roles"),
        ("zohoapi", "0004_alter_invoicedata_customer_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=155)),
                ("phone", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=254)),
                ("vendor_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.profile",
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_vendor_from_coach_profiles),
    ]
