# Generated by Django 4.1.7 on 2024-02-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapi', '0007_poreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedata',
            name='vendor_pan',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
