# Generated by Django 4.1.7 on 2024-02-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapi', '0008_invoicedata_vendor_pan'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_upload_invoice_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
