# Generated by Django 4.1.7 on 2024-02-27 13:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapi', '0008_invoicedata_vendor_pan'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedata',
            name='attatched_invoice',
            field=models.FileField(blank=True, default='', upload_to='pdf_files', validators=[api.models.validate_pdf_extension]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_upload_invoice_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
