# Generated by Django 4.1.7 on 2024-02-27 07:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapi', '0009_vendor_is_upload_invoice_allowed_vendor_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedata',
            name='attatched_invoice',
            field=models.FileField(blank=True, default='', upload_to='pdf_files', validators=[api.models.validate_pdf_extension]),
        ),
    ]
