# Generated by Django 4.1.7 on 2024-03-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapi', '0011_vendor_hsn_or_sac'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
    ]
