# Generated by Django 4.1.7 on 2024-03-22 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0022_schedularbatch_nudge_frequency_and_more'),
        ('zohoapi', '0012_ordersandprojectmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersandprojectmapping',
            name='schedular_project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedularApi.schedularproject'),
        ),
    ]
