# Generated by Django 4.1.7 on 2024-04-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapi', '0012_vendor_active_inactive_ordersandprojectmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_order_id', models.CharField(default=None, max_length=200)),
                ('sales_order_number', models.CharField(default=None, max_length=200)),
                ('line_item_id', models.CharField(default=None, max_length=200)),
                ('client_name', models.CharField(blank=True, default=None, max_length=200)),
                ('line_item_description', models.TextField(blank=True, default=None)),
                ('due_date', models.DateField(blank=True, default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoicedata',
            name='tax_names',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vendor',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
    ]
