# Generated by Django 4.1.7 on 2024-04-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapi', '0012_vendor_active_inactive_ordersandprojectmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedata',
            name='tax_names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
