# Generated by Django 4.1.7 on 2024-04-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapi', '0013_invoicedata_tax_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_order_id', models.CharField(default=None, max_length=200)),
                ('sales_order_number', models.CharField(default=None, max_length=200)),
                ('line_item_id', models.CharField(default=None, max_length=200)),
                ('client_name', models.CharField(blank=True, default=None, max_length=200)),
                ('line_item_description', models.TextField(blank=True, default=None)),
                ('due_date', models.DateField(blank=True, default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
