# Generated by Django 4.1.7 on 2024-05-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapi', '0013_billlineitem_clientinvoicelineitem_lineitems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billlineitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='clientinvoicelineitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderlineitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderlineitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderlineitem',
            name='quantity_billed',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderlineitem',
            name='quantity_cancelled',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='total_quantity',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderlineitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderlineitem',
            name='quantity_backordered',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderlineitem',
            name='quantity_cancelled',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderlineitem',
            name='quantity_invoiced',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=19, null=True),
        ),
    ]
