# Generated by Django 4.1.7 on 2024-05-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapi', '0014_alter_billlineitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='terms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
