# Generated by Django 4.1.7 on 2024-05-03 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapi', '0014_alter_bill_notes_alter_bill_terms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterModelOptions(
            name='clientinvoice',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterModelOptions(
            name='zohocustomer',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterModelOptions(
            name='zohovendor',
            options={'ordering': ['-created_time']},
        ),
    ]
