# Generated by Django 4.1.7 on 2024-05-07 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0027_alter_handoverdetails_project_type'),
        ('api', '0057_alter_project_project_type'),
        ('zohoapi', '0015_alter_bill_options_alter_clientinvoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='caas_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.project'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='engagements',
            field=models.ManyToManyField(blank=True, to='api.engagement'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='schedular_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedularApi.schedularproject'),
        ),
    ]
