# Generated by Django 4.1.7 on 2024-04-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapi', '0015_alter_bill_adjustment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='purchase_order',
        ),
        migrations.AddField(
            model_name='bill',
            name='purchase_orders',
            field=models.ManyToManyField(to='zohoapi.purchaseorder'),
        ),
    ]
