# Generated by Django 4.1.7 on 2024-04-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapi', '0016_remove_bill_purchase_order_bill_purchase_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='purchase_orders',
            field=models.ManyToManyField(blank=True, to='zohoapi.purchaseorder'),
        ),
    ]
