# Generated by Django 4.1.7 on 2024-05-07 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_project_project_type'),
        ('schedularApi', '0027_alter_handoverdetails_project_type'),
        ('zohoapi', '0016_purchaseorder_caas_project_purchaseorder_engagements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.coach'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='facilitator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.facilitator'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='caas_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.project'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='schedular_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedularApi.schedularproject'),
        ),
    ]
