# Generated by Django 4.1.7 on 2024-05-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapi', '0017_purchaseorder_coach_purchaseorder_facilitator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='facilitator',
        ),
    ]
