# Generated by Django 4.1.7 on 2024-04-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapi', '0017_alter_bill_purchase_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinvoice',
            name='client_invoice_line_items',
            field=models.ManyToManyField(blank=True, to='zohoapi.clientinvoicelineitem'),
        ),
    ]
