# Generated by Django 4.1.7 on 2024-05-27 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0036_remove_handoverdetails_pre_post_assessment_and_more'),
        ('zohoapi', '0017_purchaseorder_is_guest_ctt'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='gm_sheet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedularApi.gmsheet'),
        ),
    ]
