# Generated by Django 4.1.7 on 2024-05-08 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_project_project_type'),
        ('zohoapi', '0018_remove_purchaseorder_facilitator'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='facilitator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.facilitator'),
        ),
    ]
