# Generated by Django 4.1.7 on 2024-06-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapi', '0018_salesorder_gm_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_msme',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
