# Generated by Django 4.1.7 on 2024-04-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapi', '0019_alter_billlineitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinvoice',
            name='is_backorder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
