# Generated by Django 4.1.7 on 2024-04-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapi', '0020_alter_clientinvoice_is_backorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinvoice',
            name='is_backorder',
            field=models.BooleanField(default=False),
        ),
    ]
