# Generated by Django 4.1.7 on 2024-06-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapi', '0020_purchaseorder_po_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='background',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='designation',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='linkedin_profile',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='referred_by',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
