# Generated by Django 4.1.7 on 2024-04-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapi', '0021_alter_clientinvoice_is_backorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
    ]
