# Generated by Django 4.1.7 on 2024-06-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapi', '0021_salesorder_background_salesorder_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='companies_worked_in',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
