# Generated by Django 4.1.7 on 2023-10-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestavailibilty',
            name='provided_by',
            field=models.JSONField(default=list),
        ),
    ]
