# Generated by Django 4.1.7 on 2023-10-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedularproject',
            name='is_project_structure_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
