# Generated by Django 4.1.7 on 2023-10-19 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coachingsession',
            old_name='coaching_session_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='livesession',
            old_name='live_session_order',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='livesession',
            name='zoom_id',
        ),
        migrations.AddField(
            model_name='livesession',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='livesession',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='coachingsession',
            name='booking_link',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='coachingsession',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2023, 10, 19, 10, 45, 9, 124725, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livesession',
            name='attendees',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2023, 10, 19, 10, 45, 13, 659200, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
