# Generated by Django 4.1.7 on 2023-10-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedularbatch',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
