# Generated by Django 4.1.7 on 2023-10-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0002_alter_schedularbatch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachschedularavailibilty',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
