# Generated by Django 4.1.7 on 2023-10-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0002_requestavailibilty_provided_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coachschedularavailibilty',
            old_name='request_name',
            new_name='request',
        ),
    ]
