# Generated by Django 4.1.7 on 2023-11-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0002_schedularproject_is_project_structure_finalized'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.CharField(blank=True, default='', max_length=10)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('domain', models.JSONField(blank=True, default=list)),
                ('phone_country_code', models.CharField(blank=True, default='', max_length=20)),
                ('phone', models.CharField(max_length=25)),
                ('level', models.JSONField(blank=True, default=list)),
                ('rating', models.CharField(blank=True, max_length=20)),
                ('area_of_expertise', models.JSONField(blank=True, default=list)),
                ('profile_pic', models.ImageField(blank=True, upload_to='post_images')),
                ('education', models.JSONField(blank=True, default=list)),
                ('years_of_corporate_experience', models.CharField(blank=True, max_length=20)),
                ('language', models.JSONField(blank=True, default=list)),
                ('job_roles', models.JSONField(blank=True, default=list)),
                ('city', models.JSONField(blank=True, default=list)),
                ('country', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('edited_at', models.DateField(auto_now=True)),
                ('linkedin_profile_link', models.CharField(blank=True, max_length=500)),
                ('companies_worked_in', models.JSONField(blank=True, default=list)),
                ('other_certification', models.JSONField(blank=True, default=list)),
                ('currency', models.CharField(blank=True, default='', max_length=100)),
                ('client_companies', models.JSONField(blank=True, default=list)),
                ('educational_qualification', models.JSONField(blank=True, default=list)),
                ('fees_per_hour', models.JSONField(blank=True, default=list)),
                ('fees_per_day', models.JSONField(blank=True, default=list)),
                ('topic', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
