# Generated by Django 4.1.7 on 2023-10-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0003_rename_request_name_coachschedularavailibilty_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedularsessions',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=50),
        ),
    ]
