# Generated by Django 4.1.7 on 2023-10-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0003_coachschedularavailibilty_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachschedularavailibilty',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
