# Generated by Django 4.1.7 on 2023-11-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0003_facilitator'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestavailibilty',
            name='slot_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
