# Generated by Django 4.1.7 on 2023-11-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0003_facilitator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitator',
            name='fees_per_day',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='facilitator',
            name='fees_per_hour',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
