# Generated by Django 4.1.7 on 2023-12-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0003_facilitator'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingsession',
            name='session_type',
            field=models.CharField(choices=[('laser_coaching_session', 'Laser Coaching Session'), ('mentoring_session', 'Mentoring Session')], default='laser_coaching_session', max_length=50),
        ),
        migrations.AddField(
            model_name='requestavailibilty',
            name='slot_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
# Generated by Django 4.1.7 on 2023-11-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0003_facilitator'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingsession',
            name='session_type',
            field=models.CharField(choices=[('laser_coaching_session', 'Laser Coaching Session'), ('mentoring_session', 'Mentoring Session')], default='laser_coaching_session', max_length=50),
        ),
        migrations.AddField(
            model_name='requestavailibilty',
            name='slot_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
