# Generated by Django 4.1.7 on 2023-10-20 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0003_emailtemplate_sentemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedularparticipants',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='schedularparticipants',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2023, 10, 20, 6, 14, 25, 906109, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
