# Generated by Django 4.1.7 on 2023-10-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_coach_vendor_id'),
        ('schedularApi', '0003_emailtemplate_sentemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAvailibilty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_name', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('availability', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('coach', models.ManyToManyField(blank=True, to='api.coach')),
            ],
        ),
    ]
