# Generated by Django 4.1.7 on 2023-10-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0004_alter_schedularparticipants_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedularbatch',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
