# Generated by Django 4.1.7 on 2023-10-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_coach_vendor_id'),
        ('schedularApi', '0004_requestavailibilty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coachingsession',
            old_name='order',
            new_name='coaching_session_order',
        ),
        migrations.RenameField(
            model_name='livesession',
            old_name='order',
            new_name='live_session_order',
        ),
        migrations.RemoveField(
            model_name='livesession',
            name='description',
        ),
        migrations.RemoveField(
            model_name='livesession',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='livesession',
            name='status',
        ),
        migrations.AddField(
            model_name='livesession',
            name='zoom_id',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='coachschedularavailibilty',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='attendees',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='schedularbatch',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='schedularparticipants',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='schedularproject',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='schedularsessions',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='CoachSchedularRequestAvailibilty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_name', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('availability', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('coach', models.ManyToManyField(blank=True, to='api.coach')),
            ],
        ),
    ]
