# Generated by Django 4.1.7 on 2023-11-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0004_requestavailibilty_slot_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingsession',
            name='session_type',
            field=models.CharField(choices=[('laser_coaching_session', 'Laser Coaching Session'), ('mentoring_session', 'Mentoring Session')], default='laser_coaching_session', max_length=50),
        ),
    ]
