# Generated by Django 4.1.7 on 2023-10-21 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0005_rename_order_coachingsession_coaching_session_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachschedularavailibilty',
            name='request_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedularApi.requestavailibilty'),
        ),
    ]
