# Generated by Django 4.1.7 on 2024-01-09 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_trim_emails'),
        ('schedularApi', '0006_remove_schedularsessions_enrolled_participant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarInvites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('start_datetime', models.CharField(blank=True, max_length=255, null=True)),
                ('end_datetime', models.CharField(blank=True, max_length=255, null=True)),
                ('attendees', models.JSONField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=255, null=True)),
                ('caas_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sessionrequestcaas')),
                ('live_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedularApi.livesession')),
                ('schedular_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedularApi.schedularsessions')),
            ],
        ),
    ]
