# Generated by Django 4.1.7 on 2024-01-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0007_calendarinvites'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedularproject',
            name='platform_for_sessions',
            field=models.CharField(blank=True, choices=[('system', 'System'), ('meet', 'Meet'), ('teams', 'Teams'), ('zoom', 'Zoom')], max_length=20),
        ),
    ]
