# Generated by Django 4.1.7 on 2024-01-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0009_livesession_pt_30_min_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedularproject',
            name='automated_reminder',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
