# Generated by Django 4.1.7 on 2024-01-23 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_project_automated_reminder'),
        ('schedularApi', '0010_schedularproject_automated_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='user',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='meeting_link',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RemoveField(
            model_name='schedularbatch',
            name='facilitator',
        ),
        migrations.AddField(
            model_name='schedularbatch',
            name='facilitator',
            field=models.ManyToManyField(blank=True, to='schedularApi.facilitator'),
        ),
    ]
