# Generated by Django 4.1.7 on 2024-01-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0010_schedularproject_automated_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='session_type',
            field=models.CharField(choices=[('live_session', 'Live Session'), ('check_in_session', 'Check In Session'), ('in_person_session', 'In Person Session')], default='live_session', max_length=50),
        ),
    ]
