# Generated by Django 4.1.7 on 2024-01-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0010_schedularproject_automated_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedularproject',
            name='nudges',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='schedularproject',
            name='pre_post_assessment',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
