# Generated by Django 4.1.7 on 2024-01-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0011_livesession_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedularproject',
            name='nudges',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='schedularproject',
            name='pre_post_assessment',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
