# Generated by Django 4.1.7 on 2024-01-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedularApi", "0012_schedularproject_nudges_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="livesession",
            name="meeting_link",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RemoveField(
            model_name="schedularbatch",
            name="facilitator",
        ),
        migrations.AddField(
            model_name="schedularbatch",
            name="facilitator",
            field=models.ManyToManyField(blank=True, to="schedularApi.facilitator"),
        ),
    ]
