# Generated by Django 4.1.7 on 2024-01-31 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_apilog'),
        ('schedularApi', '0013_livesession_meeting_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='user',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
    ]
