# Generated by Django 4.1.7 on 2024-02-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0014_facilitator_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livesession',
            name='session_type',
            field=models.CharField(choices=[('live_session', 'Live Session'), ('check_in_session', 'Check In Session'), ('in_person_session', 'In Person Session'), ('kickoff_session', 'Kickoff Session')], default='live_session', max_length=50),
        ),
    ]
