# Generated by Django 4.1.7 on 2024-02-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0015_schedularproject_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedularproject',
            name='automated_reminder',
        ),
        migrations.AddField(
            model_name='schedularproject',
            name='calendar_invites',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='schedularproject',
            name='email_reminder',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='schedularproject',
            name='whatsapp_reminder',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
