# Generated by Django 4.1.7 on 2024-02-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0015_schedularproject_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedularsessions',
            name='auto_generated_status',
            field=models.CharField(blank=True, default='pending', max_length=50),
        ),
    ]
