# Generated by Django 4.1.7 on 2024-02-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_standardizedfield_field_and_more'),
        ('schedularApi', '0017_schedularsessions_auto_generated_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedularbatch',
            name='facilitator',
            field=models.ManyToManyField(blank=True, to='api.facilitator'),
        ),
        migrations.DeleteModel(
            name='Facilitator',
        ),
    ]
