# Generated by Django 4.1.7 on 2024-02-22 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_remove_coach_coach_id'),
        ('schedularApi', '0018_alter_schedularbatch_facilitator_delete_facilitator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedularbatch',
            name='facilitator',
        ),
        migrations.AddField(
            model_name='livesession',
            name='facilitator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.facilitator'),
        ),
    ]
