# Generated by Django 4.1.7 on 2024-03-06 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_coachstatus_is_consent_asked_and_more'),
        ('schedularApi', '0019_remove_schedularbatch_facilitator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_expense', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='expenses/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=255)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedularApi.schedularbatch')),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.facilitator')),
                ('live_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedularApi.livesession')),
            ],
        ),
    ]
