# Generated by Django 4.1.7 on 2024-03-06 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_facilitator_coaching_experience_and_more'),
        ('schedularApi', '0019_remove_schedularbatch_facilitator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedularproject',
            name='is_finance_enabled',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='FacilitatorPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchase_order_id', models.CharField(blank=True, default='', max_length=200)),
                ('purchase_order_no', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.facilitator')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedularApi.schedularproject')),
            ],
        ),
        migrations.CreateModel(
            name='CoachPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('session_type', models.CharField(choices=[('laser_coaching_session', 'Laser Coaching Session'), ('mentoring_session', 'Mentoring Session')], default='laser_coaching_session', max_length=50)),
                ('coaching_session_number', models.IntegerField(blank=True, default=None, null=True)),
                ('order', models.IntegerField(blank=True, default=None, null=True)),
                ('purchase_order_id', models.CharField(blank=True, default='', max_length=200)),
                ('purchase_order_no', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coach')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedularApi.schedularproject')),
            ],
        ),
    ]
