# Generated by Django 4.1.7 on 2024-03-05 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_pmo_sub_role_project_junior_pmo_alter_update_pmo'),
        ('schedularApi', '0019_remove_schedularbatch_facilitator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedularproject',
            name='junior_pmo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pmo'),
        ),
        migrations.AlterField(
            model_name='schedularupdate',
            name='pmo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pmo'),
        ),
    ]
