# Generated by Django 4.1.7 on 2024-03-10 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0020_schedularproject_is_finance_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachschedularavailibilty',
            name='request',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedularApi.requestavailibilty'),
        ),
    ]
