# Generated by Django 4.1.7 on 2024-02-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0021_alter_coachpricing_coach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitatorpricing',
            name='duration',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
