# Generated by Django 4.1.7 on 2024-03-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0022_schedularbatch_nudge_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedularproject',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
