# Generated by Django 4.1.7 on 2024-04-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0023_expense_amount_expense_purchase_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='meeting_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='schedularproject',
            name='zoom_enabled',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
