# Generated by Django 4.1.7 on 2024-04-06 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_sales'),
        ('schedularApi', '0023_expense_amount_expense_purchase_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(blank=True, choices=[('caas', 'CAAS'), ('skill_training', 'Skill Training')], max_length=255, null=True)),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_mode', models.CharField(blank=True, choices=[('online', 'Online'), ('hybrid', 'Hybrid'), ('offline', 'Offline')], max_length=255, null=True)),
                ('program_type', models.CharField(blank=True, max_length=255, null=True)),
                ('logistics_manager', models.CharField(blank=True, max_length=255, null=True)),
                ('faculty_payment_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('poc_contact_details', models.CharField(blank=True, max_length=255, null=True)),
                ('audience_level', models.CharField(blank=True, max_length=255, null=True)),
                ('project_structure', models.JSONField(blank=True, default=list, null=True)),
                ('sales_order_ids', models.JSONField(blank=True, default=list, null=True)),
                ('total_training_hours', models.IntegerField(blank=True, default=0, null=True)),
                ('total_coaching_hours', models.IntegerField(blank=True, default=0, null=True)),
                ('tentative_start_date', models.DateField(blank=True, null=True)),
                ('training_duration_frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('pre_post_assessment', models.BooleanField(blank=True, default=True)),
                ('nudges', models.BooleanField(blank=True, default=True)),
                ('special_commitments', models.TextField(blank=True, null=True)),
                ('end_of_program_certification', models.BooleanField(blank=True, default=False)),
                ('billing_process_details', models.TextField(blank=True, null=True)),
                ('out_of_pocket_expenses', models.TextField(blank=True, null=True)),
                ('other_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caas_project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.project')),
                ('schedular_project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_details', to='schedularApi.schedularproject')),
            ],
            options={
                'verbose_name': 'Handover Detail',
                'verbose_name_plural': 'Handover Details',
            },
        ),
    ]
