# Generated by Django 4.1.7 on 2024-04-10 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_sales'),
        ('schedularApi', '0024_handoverdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handoverdetails',
            name='billing_process_details',
        ),
        migrations.RemoveField(
            model_name='handoverdetails',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='handoverdetails',
            name='faculty_payment_contact',
        ),
        migrations.RemoveField(
            model_name='handoverdetails',
            name='logistics_manager',
        ),
        migrations.RemoveField(
            model_name='handoverdetails',
            name='other_feedback',
        ),
        migrations.RemoveField(
            model_name='handoverdetails',
            name='program_type',
        ),
        migrations.RemoveField(
            model_name='handoverdetails',
            name='special_commitments',
        ),
        migrations.RemoveField(
            model_name='handoverdetails',
            name='total_training_hours',
        ),
        migrations.RemoveField(
            model_name='handoverdetails',
            name='training_duration_frequency',
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='hr',
            field=models.ManyToManyField(blank=True, to='api.hr'),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.organisation'),
        ),
        migrations.AlterField(
            model_name='handoverdetails',
            name='audience_level',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
    ]
