# Generated by Django 4.1.7 on 2024-04-02 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_finance_active_inactive'),
        ('schedularApi', '0024_handoverdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoverdetails',
            name='caas_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.project'),
        ),
        migrations.AlterField(
            model_name='handoverdetails',
            name='schedular_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_details', to='schedularApi.schedularproject'),
        ),
    ]
