# Generated by Django 4.1.7 on 2024-04-25 14:06

from django.db import migrations, models
import django.db.models.deletion

def populate_reminder(apps, schema_editor):
    try:
        SchedularProject = apps.get_model("schedularApi", "SchedularProject")
        SchedularBatch = apps.get_model("schedularApi", "SchedularBatch")

        for project in SchedularProject.objects.all():
            batches = SchedularBatch.objects.filter(project=project)
            for batch in batches:
                batch.email_reminder = project.email_reminder
                batch.whatsapp_reminder = project.whatsapp_reminder
                batch.calendar_invites = project.calendar_invites
                batch.save()

    except Exception as e:
        print(e)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_hr_profile_pic_pmo_profile_pic_sales_business_and_more'),
        ('schedularApi', '0024_handoverdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handoverdetails',
            name='billing_process_details',
        ),
        migrations.RemoveField(
            model_name='handoverdetails',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='handoverdetails',
            name='faculty_payment_contact',
        ),
        migrations.RemoveField(
            model_name='handoverdetails',
            name='other_feedback',
        ),
        migrations.RemoveField(
            model_name='handoverdetails',
            name='special_commitments',
        ),
        migrations.RemoveField(
            model_name='handoverdetails',
            name='total_training_hours',
        ),
        migrations.RemoveField(
            model_name='handoverdetails',
            name='training_duration_frequency',
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='coach_fee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='coach_names',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='hr',
            field=models.ManyToManyField(blank=True, to='api.hr'),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='invoice_status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='is_accepted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.organisation'),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='participant_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='po_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='project_duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='reporting_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sales'),
        ),
        migrations.AddField(
            model_name='schedularbatch',
            name='calendar_invites',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='schedularbatch',
            name='email_reminder',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='schedularbatch',
            name='whatsapp_reminder',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='handoverdetails',
            name='audience_level',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='handoverdetails',
            name='logistics_manager',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('pmo', 'PMO'), ('faculty', 'Faculty')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='handoverdetails',
            name='program_type',
            field=models.CharField(blank=True, choices=[('soft_skill_training', 'Soft skill training'), ('coaching', 'Coaching'), ('coach_training', 'Coach Training'), ('coaching_and_coach_training', 'Coaching + Coach Training')], max_length=255, null=True),
        ),
        migrations.RunPython(populate_reminder),
    ]
