# Generated by Django 4.1.7 on 2024-04-23 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_sales'),
        ('schedularApi', '0024_handoverdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.coach'),
        ),
        migrations.AddField(
            model_name='expense',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sessionrequestcaas'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedularApi.schedularbatch'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='facilitator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.facilitator'),
        ),
    ]
