# Generated by Django 4.1.7 on 2024-04-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0025_remove_handoverdetails_billing_process_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoverdetails',
            name='gm_sheet',
            field=models.FileField(blank=True, null=True, upload_to='gm_sheets/'),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='proposals',
            field=models.FileField(blank=True, null=True, upload_to='proposals/'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('created', 'Created'), ('invoiced', 'Invoiced')], default='pending', max_length=255),
        ),
    ]
