# Generated by Django 4.1.7 on 2024-05-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0025_remove_handoverdetails_billing_process_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoverdetails',
            name='is_drafted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
