# Generated by Django 4.1.7 on 2024-04-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0025_remove_handoverdetails_billing_process_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('created', 'Created'), ('invoiced', 'Invoiced')], default='pending', max_length=255),
        ),
    ]
