# Generated by Django 4.1.7 on 2024-05-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0025_remove_handoverdetails_billing_process_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handoverdetails',
            name='logistics_manager',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('meeraq', 'Meeraq'), ('faculty', 'Faculty')], max_length=255, null=True),
        ),
    ]
