# Generated by Django 4.1.7 on 2024-04-02 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0025_handoverdetails_caas_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handoverdetails',
            name='so_number',
        ),
    ]
