# Generated by Django 5.0.3 on 2024-04-11 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0025_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='request',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedularApi.requestavailibilty'),
        ),
    ]
