# Generated by Django 5.0.3 on 2024-04-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0026_schedularbatch_calendar_invites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoverdetails',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
