# Generated by Django 4.1.7 on 2024-04-16 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_sales_business'),
        ('schedularApi', '0026_schedularbatch_calendar_invites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoverdetails',
            name='is_accepted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sales'),
        ),
    ]
