# Generated by Django 4.1.7 on 2024-05-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0026_alter_handoverdetails_logistics_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handoverdetails',
            name='project_type',
            field=models.CharField(blank=True, choices=[('caas', 'CAAS'), ('skill_training', 'Skill Training'), ('COD', 'COD')], max_length=255, null=True),
        ),
    ]
