# Generated by Django 5.0.4 on 2024-05-06 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_hr_profile_pic_pmo_profile_pic_sales_business_and_more'),
        ('schedularApi', '0026_alter_handoverdetails_logistics_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoverdetails',
            name='pmo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pmo'),
        ),
    ]
