# Generated by Django 4.1.7 on 2024-05-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0026_alter_handoverdetails_logistics_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoverdetails',
            name='billing_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='course_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='details_of_delivery',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='nudge_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='other_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='pre_post_assessment_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
