# Generated by Django 4.1.7 on 2024-04-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0026_handoverdetails_gm_sheet_handoverdetails_proposals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handoverdetails',
            name='poc_contact_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
