# Generated by Django 4.1.7 on 2024-05-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0026_remove_handoverdetails_pre_post_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoverdetails',
            name='is_drafted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
