# Generated by Django 4.1.7 on 2024-04-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0027_handoverdetails_is_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='teams_meeting_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='schedularproject',
            name='teams_enabled',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
