# Generated by Django 4.1.7 on 2024-04-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0027_handoverdetails_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoverdetails',
            name='is_accepted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
