# Generated by Django 5.0.4 on 2024-05-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0027_alter_handoverdetails_poc_contact_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoverdetails',
            name='is_drafted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
