# Generated by Django 4.1.7 on 2024-05-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0027_handoverdetails_pmo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handoverdetails',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('billed', 'Billed'), ('partially_billed', 'Partially Billed')], max_length=255, null=True),
        ),
    ]
