# Generated by Django 4.1.7 on 2024-04-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0027_handoverdetails_is_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoverdetails',
            name='coach_fee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='coach_names',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='invoice_status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='logistics_manager',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('pmo', 'PMO'), ('faculty', 'Faculty')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='participant_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='po_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='program_type',
            field=models.CharField(blank=True, choices=[('soft_skill_training', 'Soft skill training'), ('coaching', 'Coaching'), ('coach_training', 'Coach Training'), ('coaching_and_coach_training', 'Coaching + Coach Training')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='project_duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='reporting_requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
