# Generated by Django 4.1.7 on 2024-05-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0028_expense_coach_expense_session_alter_expense_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='teams_meeting_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='schedularproject',
            name='teams_enabled',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
