# Generated by Django 4.1.7 on 2024-05-09 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0028_expense_coach_expense_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='request',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedularApi.requestavailibilty'),
        ),
    ]
