# Generated by Django 4.1.7 on 2024-04-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0028_handoverdetails_coach_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoverdetails',
            name='gm_sheet',
            field=models.FileField(blank=True, null=True, upload_to='gm_sheets/'),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='proposals',
            field=models.FileField(blank=True, null=True, upload_to='proposals/'),
        ),
    ]
