# Generated by Django 4.1.7 on 2024-05-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0028_expense_coach_expense_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livesession',
            name='session_type',
            field=models.CharField(choices=[('live_session', 'Live Session'), ('check_in_session', 'Check In Session'), ('in_person_session', 'In Person Session'), ('kickoff_session', 'Kickoff Session'), ('virtual_session', 'Virtual Session'), ('pre_study', 'Pre Study')], default='virtual_session', max_length=50),
        ),
    ]
