# Generated by Django 5.0.4 on 2024-05-08 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_leader_tablehiddencolumn_user_update_coach_and_more'),
        ('schedularApi', '0028_expense_coach_expense_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.TextField(blank=True, null=True)),
                ('project_type', models.CharField(blank=True, choices=[('caas', 'CAAS'), ('skill_training', 'Skill Training')], max_length=255, null=True)),
                ('project_name', models.TextField(blank=True, null=True)),
                ('revenue_structure', models.JSONField(blank=True, default=list, null=True)),
                ('cost_structure', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gmsheet_number', models.CharField(blank=True, max_length=6, null=True)),
                ('other_details', models.TextField(blank=True, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('deal_status', models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost'), ('deferred', 'Deferred')], default='pending', max_length=255)),
                ('sales', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sales')),
            ],
        ),
    ]
