# Generated by Django 4.1.7 on 2024-04-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0028_handoverdetails_coach_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handoverdetails',
            name='poc_contact_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
