# Generated by Django 5.0.4 on 2024-05-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0029_gmsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmsheet',
            name='total_profit',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
