# Generated by Django 5.0.4 on 2024-05-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0029_benchmark_standardizedfieldgmsheet_gmsheet_offering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmsheet',
            name='gross_margin',
        ),
        migrations.RemoveField(
            model_name='gmsheet',
            name='total_profit',
        ),
    ]
