# Generated by Django 4.1.7 on 2024-04-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0029_remove_handoverdetails_pre_post_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedularproject',
            name='teams_enabled',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
