# Generated by Django 5.0.4 on 2024-05-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0030_gmsheet_total_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmsheet',
            name='gross_margin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
