# Generated by Django 5.0.4 on 2024-05-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0030_remove_gmsheet_gross_margin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmsheet',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gmsheet',
            name='product_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
