# Generated by Django 4.1.7 on 2024-05-14 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_remove_projectcontract_project_delete_coachcontract_and_more'),
        ('schedularApi', '0031_alter_livesession_session_type_projectcontract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoverdetails',
            name='is_drafted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='handoverdetails',
            name='pmo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pmo'),
        ),
        migrations.AlterField(
            model_name='handoverdetails',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('billed', 'Billed'), ('partially_billed', 'Partially Billed')], max_length=255, null=True),
        ),
    ]
