# Generated by Django 5.0.4 on 2024-05-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0031_gmsheet_currency_gmsheet_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmsheet',
            name='participant_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gmsheet',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
