# Generated by Django 4.1.7 on 2024-05-18 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_remove_projectcontract_project_delete_coachcontract_and_more'),
        ('assessmentApi', '0016_assessment_unique_id'),
        ('schedularApi', '0032_handoverdetails_is_drafted_handoverdetails_pmo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('initial_status', models.CharField(choices=[('not_started', 'Not Started'), ('occasionally_doing', 'Occasionally Doing'), ('regularly_doing', 'Regularly Doing'), ('actively_pursuing', 'Actively Pursuing'), ('consistently_achieving', 'Consistently Achieving')], default='not_started', max_length=50)),
                ('current_status', models.CharField(choices=[('not_started', 'Not Started'), ('occasionally_doing', 'Occasionally Doing'), ('regularly_doing', 'Regularly Doing'), ('actively_pursuing', 'Actively Pursuing'), ('consistently_achieving', 'Consistently Achieving')], default='not_started', max_length=50)),
                ('status_updates', models.JSONField(blank=True, default=list)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedularApi.schedularbatch')),
                ('behavior', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessmentApi.behavior')),
                ('competency', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessmentApi.competency')),
                ('learner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.learner')),
            ],
        ),
    ]
