# Generated by Django 5.0.4 on 2024-05-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0032_gmsheet_participant_level_gmsheet_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='gross_margin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gmsheet',
            name='project_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='offering',
            name='mode',
            field=models.CharField(blank=True, choices=[('In_Person', 'In Person'), ('Virtual', 'Virtual'), ('Hybrid', 'Hybrid')], default='', max_length=100, null=True),
        ),
    ]
