# Generated by Django 4.1.7 on 2024-05-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0033_actionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
