# Generated by Django 4.1.7 on 2024-05-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedularApi", "0033_actionitem"),
        (
            "assessmentApi",
            "0017_assessment_batch_alter_assessment_assessment_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="handoverdetails",
            name="assessment_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schedularproject",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("skill_training", "Skill Training"),
                    ("assessment", "Assessment"),
                ],
                default="skill_training",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="handoverdetails",
            name="project_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("caas", "CAAS"),
                    ("skill_training", "Skill Training"),
                    ("COD", "COD"),
                    ("assessment", "Assessment"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="ActionItem",
        ),
    ]
