# Generated by Django 5.0.4 on 2024-05-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0033_offering_gross_margin_alter_gmsheet_project_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='mode',
            field=models.CharField(blank=True, choices=[('in_person', 'In Person'), ('virtual', 'Virtual'), ('hybrid', 'Hybrid')], default='', max_length=100, null=True),
        ),
    ]
