# Generated by Django 4.1.7 on 2024-05-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0034_handoverdetails_assessment_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoverdetails',
            name='session_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
