# Generated by Django 5.0.4 on 2024-05-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0034_alter_offering_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('assigned_to', models.CharField(blank=True, default='', max_length=255)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('other_feedback', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
