# Generated by Django 4.1.7 on 2024-05-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0035_assets_benchmark_gmsheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='is_won',
            field=models.BooleanField(default=False),
        ),
    ]
