# Generated by Django 5.0.4 on 2024-05-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0035_assets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='other_feedback',
            new_name='description',
        ),
    ]
