# Generated by Django 5.0.4 on 2024-05-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0036_rename_other_feedback_assets_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('assigned', 'Assigned'), ('lost', 'Lost'), ('damaged', 'Damaged')], default='idle', max_length=255),
        ),
    ]
