# Generated by Django 5.0.4 on 2024-05-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0037_assets_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='updates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
