# Generated by Django 4.1.7 on 2024-05-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0038_remove_benchmark_yearly_benchmark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmsheet',
            name='project_type',
            field=models.CharField(blank=True, choices=[('CAAS', 'CAAS'), ('SEEQ', 'Skill Training'), ('Coaching + Traning', 'Coaching+Training')], max_length=255, null=True),
        ),
    ]
