# Generated by Django 4.1.7 on 2024-05-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0038_employee_assets_asset_id_assets_asset_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
