# Generated by Django 5.0.4 on 2024-05-10 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0039_alter_gmsheet_project_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmsheet',
            name='cost_structure',
        ),
        migrations.RemoveField(
            model_name='gmsheet',
            name='revenue_structure',
        ),
        migrations.AlterField(
            model_name='gmsheet',
            name='gross_margin',
            field=models.CharField(blank=True, default=0, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='gmsheet',
            name='total_profit',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_structure', models.JSONField(blank=True, default=list, null=True)),
                ('cost_structure', models.JSONField(blank=True, default=list, null=True)),
                ('gm_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedularApi.gmsheet')),
            ],
        ),
    ]
