# Generated by Django 4.1.7 on 2024-06-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0039_alter_assets_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingsession',
            name='session_type',
            field=models.CharField(choices=[('laser_coaching_session', 'Laser Coaching Session'), ('mentoring_session', 'Mentoring Session'), ('action_coaching_session', 'Action Coaching Session')], default='laser_coaching_session', max_length=50),
        ),
        migrations.AlterField(
            model_name='coachpricing',
            name='session_type',
            field=models.CharField(choices=[('laser_coaching_session', 'Laser Coaching Session'), ('mentoring_session', 'Mentoring Session'), ('action_coaching_session', 'Action Coaching Session')], default='laser_coaching_session', max_length=50),
        ),
    ]
