# Generated by Django 4.1.7 on 2024-05-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0040_benchmark_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='total_profit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
