# Generated by Django 4.1.7 on 2024-06-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0042_facilitatorcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitatorcontract',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
