# Generated by Django 4.1.7 on 2024-06-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0044_remove_facilitatorcontract_project_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedularproject',
            name='is_ngo_project',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
