# Generated by Django 4.1.7 on 2024-06-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_facilitator_remarks'),
        ('schedularApi', '0044_remove_facilitatorcontract_project_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedularbatch',
            name='hr',
            field=models.ManyToManyField(blank=True, to='api.hr'),
        ),
    ]
