# Generated by Django 4.1.7 on 2024-06-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_coach_coaching_type_coach_competency_and_more'),
        ('schedularApi', '0045_schedularbatch_hr_schedularproject_is_ngo_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedularbatch',
            name='hr',
            field=models.ManyToManyField(blank=True, to='api.hr'),
        ),
    ]
