# Generated by Django 4.1.7 on 2024-06-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0045_schedularbatch_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedularproject',
            name='is_ngo_project',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
