# Generated by Django 4.1.7 on 2024-06-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0046_schedularbatch_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentoringSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('participant_name', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=10)),
                ('description', models.TextField()),
                ('duration', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('batch_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('faculty_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('participant_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
