# Generated by Django 4.1.7 on 2024-06-25 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_chathistory_user_type'),
        ('schedularApi', '0047_mentoringsessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='active_inactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
    ]
