# Generated by Django 4.1.7 on 2024-06-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0050_remove_managementtask_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managementtask',
            old_name='groups',
            new_name='group',
        ),
    ]
