# Generated by Django 4.1.7 on 2024-06-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0051_rename_groups_managementtask_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementtask',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementtask',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('not_done', 'Not Done')], default='idle', max_length=20),
        ),
    ]
