# Generated by Django 4.1.7 on 2024-06-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0052_managementtask_start_date_managementtask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementtask',
            name='group',
            field=models.ManyToManyField(null=True, to='schedularApi.group'),
        ),
    ]
