# Generated by Django 4.1.7 on 2024-06-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0053_alter_managementtask_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementtask',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='schedularApi.group'),
        ),
    ]
