# Generated by Django 4.1.7 on 2024-06-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0054_alter_managementtask_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementtask',
            name='deadline',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='managementtask',
            name='start_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
