# Generated by Django 4.1.7 on 2024-06-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0055_alter_managementtask_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='function',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('head', 'Head'), ('team_member', 'Team Member')], default='team_member', max_length=11),
        ),
    ]
