# Generated by Django 4.1.7 on 2024-06-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0056_employee_function_employee_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementtask',
            name='group',
        ),
        migrations.AddField(
            model_name='managementtask',
            name='employee',
            field=models.ManyToManyField(blank=True, null=True, to='schedularApi.employee'),
        ),
        migrations.AlterField(
            model_name='group',
            name='employees',
            field=models.ManyToManyField(related_name='employee', to='schedularApi.employee'),
        ),
    ]
