# Generated by Django 4.1.7 on 2024-06-26 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_alter_standardizedfield_field'),
        ('schedularApi', '0057_remove_managementtask_group_managementtask_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='caas_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caas_groups', to='api.project'),
        ),
        migrations.AddField(
            model_name='group',
            name='seeq_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seeq_groups', to='schedularApi.schedularproject'),
        ),
        migrations.AlterField(
            model_name='group',
            name='employees',
            field=models.ManyToManyField(related_name='groups', to='schedularApi.employee'),
        ),
    ]
