# Generated by Django 4.1.7 on 2024-06-27 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0059_group_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementtask',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedularApi.group'),
        ),
    ]
