# Generated by Django 4.1.7 on 2024-06-27 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0060_managementtask_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementtask',
            name='employee',
        ),
        migrations.AddField(
            model_name='managementtask',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedularApi.employee'),
        ),
    ]
