# Generated by Django 4.1.7 on 2024-06-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0061_remove_managementtask_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementtask',
            name='efficiency',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='managementtask',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('low', 'Low'), ('medium', 'Medium')], default='low', max_length=20),
        ),
    ]
