# Generated by Django 4.1.7 on 2024-06-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0062_managementtask_efficiency_managementtask_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='organisation',
            field=models.CharField(choices=[('ctt', 'CTT'), ('meeraq', 'Meeraq')], default='ctt', max_length=6),
        ),
    ]
