# Generated by Django 4.1.7 on 2024-06-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0063_employee_organisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managementtask',
            old_name='efficiency',
            new_name='actual_effort',
        ),
        migrations.AddField(
            model_name='managementtask',
            name='effort',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='organisation',
            field=models.CharField(choices=[('ctt', 'CTT'), ('meeraq', 'Meeraq')], default='meeraq', max_length=6),
        ),
        migrations.AlterField(
            model_name='managementtask',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='idle', max_length=20),
        ),
    ]
