# Generated by Django 4.1.7 on 2024-06-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0065_remove_managementtask_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementtask',
            name='actual_end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='managementtask',
            name='actual_start_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
