# Generated by Django 4.1.7 on 2024-06-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0066_managementtask_actual_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='batch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='organisation',
            field=models.CharField(choices=[('ctt', 'CTT'), ('meeraq', 'Meeraq')], default='ctt', max_length=6),
        ),
    ]
