# Generated by Django 4.1.7 on 2024-06-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0067_group_batch_group_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
    ]
