# Generated by Django 4.1.7 on 2023-10-18 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0016_alter_learner_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('assessment_type', models.CharField(blank=True, choices=[('self', 'Self'), ('360', '360')], max_length=10)),
                ('number_of_observers', models.PositiveIntegerField(blank=True, null=True)),
                ('assessment_end_date', models.CharField(blank=True, max_length=255)),
                ('descriptive_questions', models.JSONField(blank=True, default=list)),
                ('rating_type', models.CharField(blank=True, choices=[('1-5', '1-5'), ('1-10', '1-10')], max_length=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='draft', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_question', models.TextField()),
                ('observer_question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessmentApi.competency')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questions', models.ManyToManyField(blank=True, to='assessmentApi.question')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_response', models.JSONField(blank=True, default=dict)),
                ('observer_response', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assessmentApi.assessment')),
                ('observer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assessmentApi.observer')),
                ('participant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.learner')),
                ('questionnaire', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assessmentApi.questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantObserverMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observers', models.ManyToManyField(blank=True, to='assessmentApi.observer')),
                ('participant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.learner')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='participants_observers',
            field=models.ManyToManyField(blank=True, to='assessmentApi.participantobservermapping'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='questionnaire',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assessmentApi.questionnaire'),
        ),
    ]
