# Generated by Django 4.1.7 on 2023-11-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0002_remove_assessment_rating_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='label',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
