# Generated by Django 4.1.7 on 2023-11-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0002_remove_assessment_rating_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='participant_view_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
