# Generated by Django 4.1.7 on 2023-10-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0002_observerresponse_participantresponse_delete_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observerresponse',
            name='questionnaire',
        ),
        migrations.RemoveField(
            model_name='participantresponse',
            name='questionnaire',
        ),
    ]
