# Generated by Django 4.1.7 on 2023-10-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0003_remove_observerresponse_questionnaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observer',
            name='phone',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='observer',
            name='type',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('reportee', 'Reportee'), ('peer', 'Peer')], max_length=10),
        ),
    ]
