# Generated by Django 4.1.7 on 2023-10-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0003_questionnaire_name_alter_questionnaire_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='questions',
            field=models.ManyToManyField(blank=True, to='assessmentApi.question'),
        ),
    ]
