# Generated by Django 4.1.7 on 2023-11-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0003_assessment_participant_view_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='label',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
