# Generated by Django 4.1.7 on 2023-11-09 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0004_question_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='competency',
            name='behaviors',
        ),
        migrations.AddField(
            model_name='competency',
            name='behaviors',
            field=models.ManyToManyField(blank=True, to='assessmentApi.behavior'),
        ),
        migrations.AlterField(
            model_name='question',
            name='behavior',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assessmentApi.behavior'),
        ),
    ]
