# Generated by Django 4.1.7 on 2023-10-14 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_project_project_description'),
        ('assessmentApi', '0004_alter_questionnaire_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('assessment_type', models.CharField(blank=True, choices=[('self', 'Self'), ('360', '360')], max_length=10)),
                ('number_of_observers', models.PositiveIntegerField(blank=True, null=True)),
                ('assessment_end_date', models.CharField(blank=True, max_length=255)),
                ('descriptive_questions', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(blank=True, to='api.learner')),
                ('questionnaire', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assessmentApi.questionnaire')),
            ],
        ),
    ]
