# Generated by Django 4.1.7 on 2023-10-22 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_learner_phone'),
        ('assessmentApi', '0004_observer_phone_observer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observer',
            name='type',
        ),
        migrations.CreateModel(
            name='ParticipantObserverType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('manager', 'Manager'), ('reportee', 'Reportee'), ('peer', 'Peer')], max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observers', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assessmentApi.observer')),
                ('participant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.learner')),
            ],
        ),
    ]
