# Generated by Django 4.1.7 on 2023-10-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0005_remove_observer_type_participantobservertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, choices=[('self', 'Self'), ('360', '360')], max_length=10),
        ),
    ]
