# Generated by Django 4.1.7 on 2023-10-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0005_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='rating_type',
            field=models.CharField(blank=True, choices=[('1-5', '1-5'), ('1-10', '1-10')], max_length=5),
        ),
    ]
