# Generated by Django 4.1.7 on 2023-11-13 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0005_behavior_remove_competency_behaviors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObserverTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=225)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='reverse_question',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='observer_types',
            field=models.ManyToManyField(blank=True, to='assessmentApi.observertypes'),
        ),
        migrations.AlterField(
            model_name='participantobservertype',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assessmentApi.observertypes'),
        ),
    ]
