# Generated by Django 4.1.7 on 2023-11-09 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0005_behavior_remove_competency_behaviors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='behavior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessmentApi.behavior'),
        ),
    ]
