# Generated by Django 4.1.7 on 2023-10-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0006_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='observer_question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
