# Generated by Django 4.1.7 on 2024-01-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0007_assessmentnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assessment_start_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assessment',
            name='automated_reminder',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
