# Generated by Django 4.1.7 on 2024-01-05 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_trim_emails'),
        ('assessmentApi', '0007_assessmentnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assessment_start_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_timing',
            field=models.CharField(choices=[('pre', 'Pre-Assessment'), ('post', 'Post-Assessment'), ('none', 'None')], default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='assessment',
            name='automated_reminder',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='pre_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessmentApi.assessment'),
        ),
        migrations.CreateModel(
            name='ParticipantUniqueId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=225, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assessmentApi.assessment')),
                ('participant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.learner')),
            ],
        ),
    ]
