# Generated by Django 4.1.7 on 2023-10-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0007_alter_question_observer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='type',
            field=models.CharField(blank=True, choices=[('self', 'Self'), ('360', '360')], max_length=10),
        ),
    ]
