# Generated by Django 4.1.7 on 2024-01-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0008_assessment_assessment_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assessment_timing',
            field=models.CharField(choices=[('pre', 'Pre-Assessment'), ('post', 'Post-Assessment'), ('none', 'None')], default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='assessment',
            name='pre_assessment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
