# Generated by Django 4.1.7 on 2023-10-27 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_learner_phone'),
        ('assessmentApi', '0009_observeruniqueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='hr',
            field=models.ManyToManyField(blank=True, to='api.hr'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.organisation'),
        ),
    ]
