# Generated by Django 4.1.7 on 2023-10-18 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0009_participant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantobservermapping',
            name='participant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assessmentApi.participant'),
        ),
    ]
