# Generated by Django 4.1.7 on 2024-01-09 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_trim_emails'),
        ('assessmentApi', '0009_question_correct_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantReleasedResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assessmentApi.assessment')),
                ('participants', models.ManyToManyField(blank=True, to='api.learner')),
            ],
        ),
    ]
