# Generated by Django 4.1.7 on 2024-01-04 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0009_assessment_assessment_timing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='pre_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessmentApi.assessment'),
        ),
    ]
