# Generated by Django 4.1.7 on 2023-10-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0010_assessment_hr_assessment_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='competency',
            name='behaviors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='competency',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
