# Generated by Django 4.1.7 on 2024-01-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0010_participantreleasedresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='initial_reminder',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
