# Generated by Django 4.1.7 on 2024-01-04 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_trim_emails'),
        ('assessmentApi', '0010_alter_assessment_pre_assessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantUniqueId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=225, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assessmentApi.assessment')),
                ('participant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.learner')),
            ],
        ),
    ]
