# Generated by Django 4.1.7 on 2023-10-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0011_competency_behaviors_competency_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='behavior',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='question',
            name='rating_type',
            field=models.CharField(blank=True, choices=[('1-5', '1-5'), ('1-10', '1-10')], max_length=5),
        ),
    ]
