# Generated by Django 4.1.7 on 2024-03-01 07:56

from django.db import migrations, models


from assessmentApi.models import Question, Questionnaire
from django.db import transaction


def update_field_correct_answer_and_populate_rating_type(apps, schema_editor):
    try:
        with transaction.atomic():

            for question in Question.objects.all():
                prev_correct_answer = question.correct_answer
                if prev_correct_answer:
                    question.correct_answer = [str(prev_correct_answer)]
                    question.response_type = "correct_answer"
                else:
                    question.response_type = "rating_type"

                question.save()

            for questionnaire in Questionnaire.objects.filter(
                questions_type="single_correct"
            ):
                questionnaire.questions_type = "correct_answer_type"
                questionnaire.save()

    except Exception as e:
        print(str(e))


class Migration(migrations.Migration):

    dependencies = [
        ("assessmentApi", "0012_questionnaire_questions_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionnaire",
            name="questions_type",
        ),
        migrations.AddField(
            model_name="question",
            name="response_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("correct_answer", "Correct Answer"),
                    ("rating_type", "Rating Type"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(update_field_correct_answer_and_populate_rating_type),
    ]
