# Generated by Django 4.1.7 on 2024-02-28 05:47

from django.db import migrations, models

from assessmentApi.models import Question, Questionnaire
from django.db import transaction


def update_field_correct_answer(apps, schema_editor):
    try:
        with transaction.atomic():

            for question in Question.objects.all():
                prev_correct_answer = question.correct_answer
                if prev_correct_answer:
                    question.correct_answer = [str(prev_correct_answer)]
                    question.save()

            for questionnaire in Questionnaire.objects.filter(
                questions_type="single_correct"
            ):
                questionnaire.questions_type = "correct_answer_type"
                questionnaire.save()

    except Exception as e:
        print(str(e))


class Migration(migrations.Migration):

    dependencies = [
        ("assessmentApi", "0012_questionnaire_questions_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="questions_type",
            field=models.CharField(
                choices=[
                    ("correct_answer_type", " Correct Answer Type"),
                    ("rating_type", "Rating Type"),
                ],
                default="correct_answer_type",
                max_length=255,
            ),
        ),
        migrations.RunPython(update_field_correct_answer),
    ]
