# Generated by Django 5.0.3 on 2024-03-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0013_remove_questionnaire_questions_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
