# Generated by Django 4.1.7 on 2024-03-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0013_remove_questionnaire_questions_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='automated_reminder',
        ),
        migrations.AddField(
            model_name='assessment',
            name='email_reminder',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='reminders',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assessment',
            name='whatsapp_reminder',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
