# Generated by Django 4.1.7 on 2024-05-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0014_remove_assessment_automated_reminder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='response_type',
            field=models.CharField(blank=True, choices=[('correct_answer', 'Correct Answer'), ('rating_type', 'Rating Type'), ('descriptive', 'Descriptive')], max_length=50),
        ),
    ]
