# Generated by Django 4.1.7 on 2024-05-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0015_alter_question_response_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='unique_id',
            field=models.CharField(default='', max_length=225),
        ),
    ]
