# Generated by Django 4.1.7 on 2024-05-20 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0033_handoverdetails_assessment_details_and_more'),
        ('assessmentApi', '0015_alter_question_response_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedularApi.schedularbatch'),
        ),
    ]
