# Generated by Django 4.1.7 on 2024-05-20 15:19

from django.db import migrations, models
import django.db.models.deletion


def populate_action_items(apps, schema_editor):
    try:
        ActionItem = apps.get_model("schedularApi", "ActionItem")

        action_items = ActionItem.objects.all()
        for action_item in action_items:
            new_action_item = ActionItem.objects.create(
                text=action_item.text,
                initial_status=action_item.initial_status,
                current_status=action_item.current_status,
                status_updates=action_item.status_updates,
                completion_date=action_item.completion_date,
                learner=action_item.learner,
                batch=action_item.batch,
                competency=action_item.competency,
                behavior=action_item.behavior,
            )
    except Exception as e:
        print(e)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0061_remove_projectcontract_project_delete_coachcontract_and_more"),
        ("assessmentApi", "0016_assessment_unique_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="schedularApi.schedularbatch",
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="assessment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("self", "Self"),
                    ("360", "360"),
                    ("270", "270"),
                    ("90", "90"),
                    ("180", "180"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ActionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "initial_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("occasionally_doing", "Occasionally Doing"),
                            ("regularly_doing", "Regularly Doing"),
                            ("actively_pursuing", "Actively Pursuing"),
                            ("consistently_achieving", "Consistently Achieving"),
                        ],
                        default="not_started",
                        max_length=50,
                    ),
                ),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("occasionally_doing", "Occasionally Doing"),
                            ("regularly_doing", "Regularly Doing"),
                            ("actively_pursuing", "Actively Pursuing"),
                            ("consistently_achieving", "Consistently Achieving"),
                        ],
                        default="not_started",
                        max_length=50,
                    ),
                ),
                ("status_updates", models.JSONField(blank=True, default=list)),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="schedularApi.schedularbatch",
                    ),
                ),
                (
                    "behavior",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assessmentApi.behavior",
                    ),
                ),
                (
                    "competency",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assessmentApi.competency",
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.learner",
                    ),
                ),
            ],
        ),
        migrations.RunPython(populate_action_items)
    ]
