# Generated by Django 4.1.7 on 2024-05-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0016_assessment_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(blank=True, choices=[('self', 'Self'), ('360', '360'), ('270', '270'), ('90', '90'), ('180', '180')], max_length=10),
        ),
    ]
