# Generated by Django 4.1.7 on 2024-05-21 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0034_handoverdetails_assessment_details_and_more'),
        ('assessmentApi', '0017_assessment_batch_alter_assessment_assessment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchCompetencyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedularApi.schedularbatch')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessmentApi.competency')),
                ('selected_behaviors', models.ManyToManyField(blank=True, to='assessmentApi.behavior')),
            ],
        ),
    ]
