# Generated by Django 4.1.7 on 2024-05-27 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_project_nudge_frequency_project_nudge_periodic_task_and_more'),
        ('assessmentApi', '0018_batchcompetencyassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessmentApi.questionnaire'),
        ),
        migrations.CreateModel(
            name='ProjectAssessmentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessments', models.ManyToManyField(blank=True, to='assessmentApi.assessment')),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
    ]
