# Generated by Django 4.1.7 on 2024-05-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0019_alter_assessment_questionnaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observerresponse',
            name='temp_observer_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='participantresponse',
            name='temp_participant_response',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
