# Generated by Django 4.1.7 on 2024-05-27 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0019_projectassessmentmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessmentApi.questionnaire'),
        ),
    ]
