# Generated by Django 4.1.7 on 2024-06-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0021_actionitem_remarks_assessment_automated_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='brand',
            field=models.CharField(choices=[('Meeraq', 'Meeraq'), ('CTT', 'CTT')], default='Meeraq', max_length=255),
        ),
        migrations.AddField(
            model_name='assessment',
            name='is_quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='passing_percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='shuffle_questions',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='type',
            field=models.CharField(blank=True, choices=[('self', 'Self'), ('360', '360'), ('quiz', 'Quiz')], max_length=10),
        ),
    ]
