# Generated by Django 4.1.7 on 2024-06-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0022_assessment_brand_assessment_is_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='passing_percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
