# Generated by Django 4.1.7 on 2023-12-07 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0032_pastsessionactivity_session_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('selected_options', models.JSONField(default=list)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('public', 'Public')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('public', 'Public')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('public', 'Public')], max_length=20)),
                ('lesson_type', models.CharField(choices=[('text', 'Text Lesson'), ('quiz', 'Quiz Lesson'), ('live_session', 'Live Session'), ('laser_coaching', 'Laser Coaching Session'), ('feedback', 'Feedback'), ('assessment', 'Assessment'), ('video', 'Video')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('course_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.coursetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('options', models.JSONField(default=list)),
                ('type', models.CharField(choices=[('single_correct_answer', 'Single Correct Answer'), ('multiple_correct_answer', 'Multiple Correct Answers'), ('rating_1_to_5', '1 to 5 Rating'), ('rating_1_to_10', '1 to 10 Rating'), ('descriptive_answer', 'Descriptive Answer')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuizLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
                ('questions', models.ManyToManyField(to='courses.question')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.video')),
            ],
        ),
        migrations.CreateModel(
            name='TextLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='QuizLessonResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('answers', models.ManyToManyField(to='courses.answer')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.learner')),
                ('quiz_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.quizlesson')),
            ],
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('meeting_link', models.URLField()),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='LaserCoachingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('booking_link', models.URLField()),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackLessonResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('answers', models.ManyToManyField(to='courses.answer')),
                ('feedback_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.feedbacklesson')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.learner')),
            ],
        ),
        migrations.AddField(
            model_name='feedbacklesson',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='feedbacklesson',
            name='questions',
            field=models.ManyToManyField(to='courses.question'),
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('completed_lessons', models.JSONField(blank=True, default=list)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.learner')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursetemplate'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(blank=True, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.question'),
        ),
    ]
