# Generated by Django 4.1.7 on 2023-12-11 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0004_coachingsession_session_type_and_more'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSessionLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
                ('live_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedularApi.livesession')),
            ],
        ),
        migrations.RemoveField(
            model_name='lasercoachingsession',
            name='booking_link',
        ),
        migrations.RemoveField(
            model_name='lasercoachingsession',
            name='description',
        ),
        migrations.AddField(
            model_name='course',
            name='batch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schedularApi.schedularbatch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lasercoachingsession',
            name='coaching_session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schedularApi.coachingsession'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LiveSession',
        ),
    ]
