# Generated by Django 4.1.7 on 2023-11-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_textlesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textlesson',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
