# Generated by Django 4.1.7 on 2023-12-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_resources_pdflesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('text', 'Text Lesson'), ('quiz', 'Quiz Lesson'), ('live_session', 'Live Session'), ('laser_coaching', 'Laser Coaching Session'), ('feedback', 'Feedback'), ('assessment', 'Assessment'), ('video', 'Video'), ('ppt', 'PPT')], max_length=20),
        ),
    ]
