# Generated by Django 4.1.7 on 2023-11-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_livesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livesession',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
