# Generated by Django 4.1.7 on 2023-12-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='drip_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
