# Generated by Django 4.1.7 on 2023-11-21 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lasercoachingsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('options', models.JSONField(default=list)),
                ('type', models.CharField(choices=[('single_correct_answer', 'Single Correct Answer'), ('multiple_correct_answer', 'Multiple Correct Answers'), ('rating_1_to_5', '1 to 5 Rating'), ('rating_1_to_10', '1 to 10 Rating'), ('descriptive_answer', 'Descriptive Answer')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuizLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
                ('questions', models.ManyToManyField(to='courses.question')),
            ],
        ),
    ]
