# Generated by Django 4.1.7 on 2024-01-12 16:07

from django.db import migrations, models
import uuid
from courses.models import FeedbackLesson

def populate_unique_ids(apps, schema_editor):
    for feedback_lesson in FeedbackLesson.objects.all():
        # Generate a unique ID using uuid
        feedback_lesson.unique_id = uuid.uuid4()

        feedback_lesson.save()

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacklesson',
            name='unique_id',
            field=models.CharField(blank=True, max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('single_correct_answer', 'Single Correct Answer'), ('multiple_correct_answer', 'Multiple Correct Answers'), ('rating_1_to_5', '1 to 5 Rating'), ('rating_1_to_10', '1 to 10 Rating'), ('descriptive_answer', 'Descriptive Answer'), ('rating_0_to_10', '0 to 10 Rating')], max_length=255),
        ),
        migrations.RunPython(populate_unique_ids),
    ]
