# Generated by Django 4.1.7 on 2023-11-21 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_question_quizlesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
                ('questions', models.ManyToManyField(to='courses.question')),
            ],
        ),
    ]
