# Generated by Django 4.1.7 on 2024-01-21 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0011_assessment_initial_reminder'),
        ('courses', '0008_thinkificlessoncompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assessment_modal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_modal', to='assessmentApi.assessment'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='type',
            field=models.CharField(choices=[('pre', 'Pre-Assessment'), ('post', 'Post-Assessment'), ('none', 'None')], default='none', max_length=255),
        ),
    ]
