# Generated by Django 4.1.7 on 2024-01-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_thinkificlessoncompleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThinkificLessonCompleted',
        ),
    ]
