# Generated by Django 4.1.7 on 2024-01-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_thinkificlessoncompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='is_certificate_allowed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
