# Generated by Django 4.1.7 on 2023-11-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_courseenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='completed_lessons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
