# Generated by Django 4.1.7 on 2024-01-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_assessment_assessment_modal_assessment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='is_certificate_allowed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
