# Generated by Django 4.1.7 on 2024-01-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_courseenrollment_is_certificate_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
        migrations.AddField(
            model_name='coursetemplate',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
    ]
