# Generated by Django 4.1.7 on 2024-01-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_course_course_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolesson',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
