# Generated by Django 4.1.7 on 2023-11-23 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_videolesson'),
        ('courses', '0013_certificate'),
    ]

    operations = [
    ]
