# Generated by Django 4.1.7 on 2024-02-15 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0018_alter_schedularbatch_facilitator_delete_facilitator'),
        ('courses', '0013_pdflesson_content_videolesson_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacklesson',
            name='live_session',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedularApi.livesession'),
        ),
    ]
