# Generated by Django 4.1.7 on 2023-11-23 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_standardizedfield_standardizedfieldrequest'),
        ('courses', '0013_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='learner',
        ),
        migrations.CreateModel(
            name='QuizLessonResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('answers', models.ManyToManyField(to='courses.answer')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.learner')),
                ('quiz_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.quizlesson')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackLessonResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('answers', models.ManyToManyField(to='courses.answer')),
                ('feedback_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.feedbacklesson')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.learner')),
            ],
        ),
    ]
