# Generated by Django 4.1.7 on 2023-11-23 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_merge_0011_videolesson_0013_certificate'),
        ('courses', '0014_remove_answer_learner_quizlessonresponse_and_more'),
    ]

    operations = [
    ]
