# Generated by Django 4.1.7 on 2023-11-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_merge_20231123_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
