# Generated by Django 4.1.7 on 2024-03-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_assignmentlesson_alter_lesson_lesson_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='drip_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
