# Generated by Django 4.1.7 on 2024-03-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_lesson_lesson_type_facilitatorlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='drip_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
