# Generated by Django 4.1.7 on 2024-03-09 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0020_schedularproject_is_finance_enabled_and_more'),
        ('api', '0046_facilitator_is_approved'),
        ('courses', '0016_alter_lesson_lesson_type_facilitatorlesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questions', models.ManyToManyField(to='courses.question')),
            ],
        ),
        migrations.CreateModel(
            name='CoachingSessionsFeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('answers', models.ManyToManyField(to='courses.answer')),
                ('caas_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sessionrequestcaas')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.feedback')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.learner')),
                ('schedular_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedularApi.schedularsessions')),
            ],
        ),
    ]
