# Generated by Django 4.1.7 on 2024-03-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedularApi', '0019_remove_schedularbatch_facilitator_and_more'),
        ('courses', '0017_lesson_drip_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='live_session',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedularApi.livesession'),
        ),
    ]
