# Generated by Django 4.1.7 on 2024-03-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_remove_course_nudge_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_mandatory',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
