# Generated by Django 4.1.7 on 2024-03-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_remove_course_nudge_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nudge',
            name='is_swithced_on',
            field=models.BooleanField(default=True),
        ),
    ]
