# Generated by Django 4.1.7 on 2024-05-07 18:10

from django.db import migrations, models
import uuid


def populate_unique_ids(apps, schema_editor):
    Nudge = apps.get_model("courses", "Nudge")
    for nudge in Nudge.objects.all():
        if not nudge.unique_id:
            nudge.unique_id = str(uuid.uuid4())
            nudge.save()


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0020_nudge_is_switched_on_nudge_trigger_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="nudge",
            name="learner_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="nudge",
            name="unique_id",
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.RunPython(populate_unique_ids),
    ]
