# Generated by Django 4.1.7 on 2024-03-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_nudge_is_switched_on_nudge_trigger_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_mandatory',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
