# Generated by Django 4.1.7 on 2024-03-18 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_nudge_is_swithced_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nudge',
            old_name='is_swithced_on',
            new_name='is_switched_on',
        ),
    ]
