# Generated by Django 4.1.7 on 2024-04-24 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_project_nudges_project_post_assessment_and_more'),
        ('courses', '0020_nudge_is_switched_on_nudge_trigger_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='nudge',
            name='caas_project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
    ]
