# Generated by Django 4.1.7 on 2024-05-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_nudge_is_switched_on_nudge_trigger_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='nudge',
            name='learner_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='nudge',
            name='unique_id',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
