# Generated by Django 4.1.7 on 2024-05-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_nudge_is_switched_on_nudge_trigger_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
        migrations.AddField(
            model_name='coursetemplate',
            name='course_image',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
    ]
