# Generated by Django 4.1.7 on 2024-03-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_rename_is_swithced_on_nudge_is_switched_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='nudge',
            name='trigger_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
