# Generated by Django 4.1.7 on 2024-05-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_nudge_learner_ids_nudge_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
        migrations.AddField(
            model_name='coursetemplate',
            name='course_image',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
    ]
