# Generated by Django 4.1.7 on 2024-05-20 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_course_course_image_coursetemplate_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CttFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Feedback', max_length=225, null=True)),
                ('unique_id', models.CharField(blank=True, max_length=225)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='draft', max_length=255)),
                ('ctt_batch', models.IntegerField(blank=True, null=True)),
                ('session_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questions', models.ManyToManyField(to='courses.question')),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, default='Feedback', max_length=225, null=True),
        ),
        migrations.CreateModel(
            name='CttFeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctt_user', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answers', models.ManyToManyField(to='courses.answer')),
                ('ctt_feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.cttfeedback')),
            ],
        ),
    ]
