# Generated by Django 4.1.7 on 2024-05-27 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
      
        ('courses', '0023_cttfeedback_feedback_name_cttfeedbackresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='nudge',
            name='caas_project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
    ]
