# Generated by Django 4.1.7 on 2024-05-20 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentApi', '0016_assessment_unique_id'),
        ('courses', '0023_cttfeedback_feedback_name_cttfeedbackresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCompetencyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessmentApi.competency')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('selected_behaviors', models.ManyToManyField(blank=True, to='assessmentApi.behavior')),
            ],
        ),
    ]
