# Generated by Django 4.1.7 on 2024-05-27 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_project_nudges_project_post_assessment_and_more'),
        ('courses', '0023_cttfeedback_feedback_name_cttfeedbackresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='nudge',
            name='caas_project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
    ]
