# Generated by Django 4.1.7 on 2024-06-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_curriculum'),
        ('schedularApi', '0041_schedularproject_unique_id'),
        ('courses', '0025_alter_nudge_content_alter_nudge_name_nudgeresources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nudgeresources',
            name='caas_project_assigned',
            field=models.ManyToManyField(blank=True, null=True, to='api.project'),
        ),
        migrations.AddField(
            model_name='nudgeresources',
            name='skill_project_assigned',
            field=models.ManyToManyField(blank=True, null=True, to='schedularApi.schedularproject'),
        ),
    ]
