# Generated by Django 4.1.7 on 2024-06-04 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_curriculum'),
        ('courses', '0025_alter_nudge_content_alter_nudge_name_nudgeresources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nudgeresources',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.curriculum'),
        ),
        migrations.AddField(
            model_name='nudgeresources',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('public', 'Public')], max_length=50, null=True),
        ),
    ]
