# Generated by Django 4.1.7 on 2024-06-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_curriculum'),
        ('courses', '0025_alter_nudge_content_alter_nudge_name_nudgeresources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nudgeresources',
            name='project_assigned',
            field=models.ManyToManyField(to='api.project'),
        ),
    ]
