# Generated by Django 4.1.7 on 2024-06-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_facilitator_remarks'),
        ('schedularApi', '0041_schedularproject_unique_id'),
        ('courses', '0026_nudgeresources_caas_project_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nudgeresources',
            name='caas_project_assigned',
            field=models.ManyToManyField(blank=True, to='api.project'),
        ),
        migrations.AlterField(
            model_name='nudgeresources',
            name='skill_project_assigned',
            field=models.ManyToManyField(blank=True, to='schedularApi.schedularproject'),
        ),
    ]
