# Generated by Django 4.1.7 on 2024-06-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_curriculum'),
        ('schedularApi', '0041_schedularproject_unique_id'),
        ('courses', '0026_nudgeresources_project_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nudgeresources',
            name='project_assigned',
        ),
        migrations.AddField(
            model_name='nudgeresources',
            name='caas_project_assigned',
            field=models.ManyToManyField(blank=True, null=True, to='api.project'),
        ),
        migrations.AddField(
            model_name='nudgeresources',
            name='skill_project_assigned',
            field=models.ManyToManyField(blank=True, null=True, to='schedularApi.schedularproject'),
        ),
    ]
