# Generated by Django 4.1.7 on 2024-06-10 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_alter_nudgeresources_caas_project_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nudge',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.video'),
        ),
        migrations.AddField(
            model_name='nudgeresources',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.video'),
        ),
    ]
