# Generated by Django 4.1.7 on 2024-06-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_alter_nudgeresources_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nudgeresources',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Open', 'Open')], default='Draft', max_length=50, null=True),
        ),
    ]
