# Generated by Django 4.1.7 on 2024-06-17 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_cttsessionattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cttfeedback',
            name='feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.feedback'),
        ),
        migrations.AddField(
            model_name='cttfeedback',
            name='program',
            field=models.CharField(choices=[('level-1', 'Level-1'), ('level-2', 'Level-2'), ('level-3', 'Level-3'), ('actc', 'ACTC')], default='', max_length=255),
        ),
    ]
