# Generated by Django 4.1.7 on 2024-06-14 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_cttfeedback_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='cttfeedback',
            name='feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.feedback'),
        ),
    ]
