# Generated by Django 4.1.7 on 2024-06-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_cttfeedback_feedback_cttfeedback_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='CttCalendarInvites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('start_datetime', models.CharField(blank=True, max_length=255, null=True)),
                ('end_datetime', models.CharField(blank=True, max_length=255, null=True)),
                ('attendees', models.JSONField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=255, null=True)),
                ('ctt_session', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
