# Generated by Django 4.1.7 on 2024-06-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_cttcalendarinvites'),
    ]

    operations = [
        migrations.CreateModel(
            name='CttParticipantPerformanceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField(blank=True, null=True)),
                ('participant', models.IntegerField(blank=True, null=True)),
                ('transcript_link', models.TextField(blank=True, null=True)),
                ('audio_link', models.TextField(blank=True, null=True)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('pass', 'Pass'), ('fail', 'Fail')], default='pending', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
