# Generated by Django 4.1.7 on 2024-06-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_cttcalendarinvites'),
    ]

    operations = [
        migrations.AddField(
            model_name='cttcalendarinvites',
            name='ctt_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
