from django.contrib import admin
from .models import (
    Pmo,
    Coach,
    Profile,
    Project,
    CoachStatus,
    Availibility,
    SessionRequestCaas,
    Notification,
    Organisation,
    Learner,
    HR,
    Engagement,
    Goal,
    Competency,
    ActionItem,
    ProfileEditActivity,
    UserLoginActivity,
    AddGoalActivity,
    AddCoachActivity,
    SentEmailActivity,
    CoachProfileTemplate,
    StandardizedField,
    StandardizedFieldRequest,
    RemoveCoachActivity,
    DeleteCoachProfileActivity,
    SessionRequestedActivity,
    PastSessionActivity,
    Template,
    ProjectContract,
    CoachContract,
    Update,
    UserToken,
    CalendarEvent,
    FinalizeCoachActivity,
    ShareCoachProfileActivity,
    CreateProjectActivity,
    Role,
    APILog,
    SuperAdmin,
    Facilitator,
    Finance,
    Task,
    Sales,
    TableHiddenColumn,
    CTTPmo,
)

# Register your models here.

admin.site.register(Pmo)
admin.site.register(Coach)
admin.site.register(Organisation)
admin.site.register(Project)
admin.site.register(Learner)
admin.site.register(Availibility)
admin.site.register(HR)
admin.site.register(Profile)
admin.site.register(Engagement)
admin.site.register(CoachStatus)
admin.site.register(SessionRequestCaas)
admin.site.register(Notification)
admin.site.register(Goal)
admin.site.register(Competency)
admin.site.register(ActionItem)
admin.site.register(ProfileEditActivity)
admin.site.register(UserLoginActivity)
admin.site.register(SentEmailActivity)
admin.site.register(AddCoachActivity)
admin.site.register(AddGoalActivity)
admin.site.register(CoachProfileTemplate)
admin.site.register(Facilitator)
admin.site.register(StandardizedField)
admin.site.register(StandardizedFieldRequest)
admin.site.register(RemoveCoachActivity)
admin.site.register(DeleteCoachProfileActivity)
admin.site.register(SessionRequestedActivity)
admin.site.register(PastSessionActivity)
admin.site.register(Template)
admin.site.register(ProjectContract)
admin.site.register(CoachContract)
admin.site.register(Update)
admin.site.register(UserToken)
admin.site.register(CalendarEvent)
admin.site.register(ShareCoachProfileActivity)
admin.site.register(CreateProjectActivity)
admin.site.register(FinalizeCoachActivity)
admin.site.register(Role)
admin.site.register(APILog)
admin.site.register(SuperAdmin)
admin.site.register(Finance)
admin.site.register(Task)
admin.site.register(Sales)
admin.site.register(TableHiddenColumn)
admin.site.register(CTTPmo)
